<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgcareerSet
//	Type                   :   Collection Class
//	Description            :   This class manages the collection of objects of class clswgcareer
//	Author                 :   NTCS Maintenance
//	Date                   :   12/01/2018
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($DOCUMENT_ROOT."classes/clswgcareer.php");
 
class clswgcareerSet
{ 
	var $awgcareer = array();
	function Add($obj)
	{
		$this->awgcareer[] = $obj;
	}
	function GetCount()
	{
		return count($this->awgcareer);
	}
	function GetItem($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgcareerSet:GetItem()";
			exit;
		}
		return $this->awgcareer[$lIndex];
	}
	function Remove($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgcareerSet:Remove()";
			exit;
		}
		for($i = $lIndex; $i < $lLastEntry; $i++)
		{
			$this->awgcareer[$i] = $this->awgcareer[$i+1];
		}
		array_pop($this->awgcareer);
	}
}
?>