<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgcontactManager
//	Type                   :   Manager Class
//	Description            :   This class implements the methods for DML operations of table wgcontact
//	Author                 :   NTCS Maintenance
//	Date                   :   11/01/2018
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($_SERVER['$DOCUMENT_ROOT']."classes/clswgcontact.php");
require_once($_SERVER['$DOCUMENT_ROOT']."classes/clswgcontactSet.php");
 
class clswgcontactManager
{
	function Savewgcontact($objwgcontact, $myConn=null)
	{
	
		$tdiscription=$objwgcontact->getdiscription();
		$semail=$objwgcontact->getemail();
		$lmobnum=$objwgcontact->getmobnum();
		$sname=$objwgcontact->getname();
		$ssubject=$objwgcontact->getsubject();
		$swebsite=$objwgcontact->getwebsite();
        
        if($tdiscription==null)
        {
           $semail="' '"; 
        }
        else
        $tdiscription="'$tdiscription'";

		if($semail==null)
			$semail="' '";
		else
			$semail="'$semail'";

		if($lmobnum==null)
			$lmobnum="' '";

		if($sname==null)
			$sname="' '";
		else
			$sname="'$sname'";

		if($ssubject==null)
			$ssubject="' '";
		else
			$ssubject="'$ssubject'";

		if($swebsite==null)
			$swebsite="' '";
		else
			$swebsite="'$swebsite'";
		$sQuery = "insert into wgcontact(discription,email,mobnum,name,subject,website) values ($tdiscription,$semail,$lmobnum,$sname,$ssubject,$swebsite)";
        //echo $sQuery;
	 @mysqli_close();
            global $DOCUMENT_ROOT;
            require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");
            //mysql_query($connection,$sQuery);
                     
            $rsltadded=0;
            if(mysqli_query($connection,$sQuery))
            {
                $rsltadded=1;
            }
            else
            {
                $rsltadded=2;
            }
             
            mysqli_close();
        return $rsltadded;    
	}
	function SavewgcontactSet($objwgcontactSet, $myConn=null)
	{
		$objwgcontact = new clswgcontact();
		$lNumRecord = $objwgcontactSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcontact = new clswgcontact();
				$objwgcontact = $objwgcontactSet->GetItem($lCount);
				
				$tdiscription=$objwgcontact->getdiscription();
				$semail=$objwgcontact->getemail();
				$lmobnum=$objwgcontact->getmobnum();
				$sname=$objwgcontact->getname();
				$ssubject=$objwgcontact->getsubject();
				$swebsite=$objwgcontact->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($ssubject==null)
					$ssubject='null';
				else
					$ssubject="'$ssubject'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";
				$sQuery = "insert into wgcontact(discription,email,mobnum,name,subject,website) values (CURRENT_TIMESTAMP,$semail,$lmobnum,$sname,$ssubject,$swebsite)";
				$rsltwgcontact = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcontactManager:SavewgcontactSet");
				$lNumTuples = pg_cmdtuples($rsltwgcontact);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
			}
			else
			{
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			pg_exec($connection,'begin');
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcontact = new clswgcontact();
				$objwgcontact = $objwgcontactSet->GetItem($lCount);
				
				$tdiscription=$objwgcontact->getdiscription();
				$semail=$objwgcontact->getemail();
				$lmobnum=$objwgcontact->getmobnum();
				$sname=$objwgcontact->getname();
				$ssubject=$objwgcontact->getsubject();
				$swebsite=$objwgcontact->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($ssubject==null)
					$ssubject='null';
				else
					$ssubject="'$ssubject'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";
				$sQuery = "insert into wgcontact(discription,email,mobnum,name,subject,website) values (CURRENT_TIMESTAMP,$semail,$lmobnum,$sname,$ssubject,$swebsite)";
				$rsltwgcontact = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcontactManager:SavewgcontactSet");
				$lNumTuples = pg_cmdtuples($rsltwgcontact);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
				pg_exec($connection,'commit');
				pg_close();
			}
			return $lTotalTuples;
	}

	function RetrievewgcontactSet($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgcontactSet = new clswgcontactSet();
		$rsltwgcontact = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcontactManager:Retrievewgcontact.");
		$lNumRows = pg_numrows($rsltwgcontact);
		if($lNumRows == 0)
		{
			pg_close();
			return $objwgcontactSet;
		}
		for($lCount = 0; $lCount < $lNumRows; $lCount++)
		{
			$objwgcontact = new clswgcontact();
			$arrwgcontact=pg_fetch_array($rsltwgcontact,$lCount);
			$objwgcontact->setdiscription($arrwgcontact[discription]);
			$objwgcontact->setemail($arrwgcontact[email]);
			$objwgcontact->setmobnum($arrwgcontact[mobnum]);
			$objwgcontact->setname($arrwgcontact[name]);
			$objwgcontact->setsubject($arrwgcontact[subject]);
			$objwgcontact->setwebsite($arrwgcontact[website]);
			$objwgcontactSet->Add($objwgcontact);
		}
		pg_close();
		return $objwgcontactSet;
	}

	function Retrievewgcontact($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgcontact = new clswgcontact();
		$rsltwgcontact = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcontactManager:Retrievewgcontact.");
		$lNumRows = pg_numrows($rsltwgcontact);
		if($lNumRows == 0)
		{
			pg_close();
			return null;
		}
			$arrwgcontact=pg_fetch_array($rsltwgcontact,0);
			$objwgcontact->setdiscription($arrwgcontact[discription]);
			$objwgcontact->setemail($arrwgcontact[email]);
			$objwgcontact->setmobnum($arrwgcontact[mobnum]);
			$objwgcontact->setname($arrwgcontact[name]);
			$objwgcontact->setsubject($arrwgcontact[subject]);
			$objwgcontact->setwebsite($arrwgcontact[website]);
		pg_close();
		return $objwgcontact;
	}

	function Updatewgcontact($objwgcontact, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$tdiscription=$objwgcontact->getdiscription();
		$semail=$objwgcontact->getemail();
		$lmobnum=$objwgcontact->getmobnum();
		$sname=$objwgcontact->getname();
		$ssubject=$objwgcontact->getsubject();
		$swebsite=$objwgcontact->getwebsite();

		if($semail==null)
			$semail='null';
		else
			$semail="'$semail'";

		if($lmobnum==null)
			$lmobnum='null';

		if($sname==null)
			$sname='null';
		else
			$sname="'$sname'";

		if($ssubject==null)
			$ssubject='null';
		else
			$ssubject="'$ssubject'";

		if($swebsite==null)
			$swebsite='null';
		else
			$swebsite="'$swebsite'";

		$sQuery = "update wgcontact set
			discription=CURRENT_TIMESTAMP,
			email=$semail,
			mobnum=$lmobnum,
			subject=$ssubject,
			website=$swebsite
			where name=$sname";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgcontact = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcontactManager:Updatewgcontact");
			$lNumTuples = pg_cmdtuples($rsltwgcontact);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgcontact = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcontactManager:Updatewgcontact");
			$lNumTuples = pg_cmdtuples($rsltwgcontact);
			pg_close();
		}
	return $lNumTuples;
	}
	function UpdatewgcontactSet($objwgcontactSet, $myConn=null)
	{
		$objwgcontact = new clswgcontact();
		$lNumRecord = $objwgcontactSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcontact = new clswgcontact();
				$objwgcontact = $objwgcontactSet->GetItem($lCount);
				
				$tdiscription=$objwgcontact->getdiscription();
				$semail=$objwgcontact->getemail();
				$lmobnum=$objwgcontact->getmobnum();
				$sname=$objwgcontact->getname();
				$ssubject=$objwgcontact->getsubject();
				$swebsite=$objwgcontact->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($ssubject==null)
					$ssubject='null';
				else
					$ssubject="'$ssubject'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";

				$sQuery = "update wgcontact set
				discription=CURRENT_TIMESTAMP,
				email=$semail,
				mobnum=$lmobnum,
				subject=$ssubject,
				website=$swebsite
				where name=$sname";
				$rsltwgcontact = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcontactManager:UpdatewgcontactSet");
				$lNumTuples = pg_cmdtuples($rsltwgcontact);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
			}
			else
			{
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			pg_exec($connection,'begin');
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcontact = new clswgcontact();
				$objwgcontact = $objwgcontactSet->GetItem($lCount);
				
				$tdiscription=$objwgcontact->getdiscription();
				$semail=$objwgcontact->getemail();
				$lmobnum=$objwgcontact->getmobnum();
				$sname=$objwgcontact->getname();
				$ssubject=$objwgcontact->getsubject();
				$swebsite=$objwgcontact->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($ssubject==null)
					$ssubject='null';
				else
					$ssubject="'$ssubject'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";
				$sQuery = "update wgcontact set
				discription=CURRENT_TIMESTAMP,
				email=$semail,
				mobnum=$lmobnum,
				subject=$ssubject,
				website=$swebsite
				where name=$sname";
				$rsltwgcontact = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcontactManager:UpdatewgcontactSet");
				$lNumTuples = pg_cmdtuples($rsltwgcontact);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
				pg_exec($connection,'commit');
				pg_close();
			}
			return $lTotalTuples;
	}

	function Deletewgcontact($obj, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$sname=$obj->getname();

		if($sname==null)
			$sname='null';
		else
			$sname="'$sname'";
		$sQuery = "delete from wgcontact
			where name=$sname";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgcontact = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcontactManager:Deletewgcontact");
			$lNumTuples = pg_cmdtuples($rsltwgcontact);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgcontact = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcontactManager:Deletewgcontact");
			$lNumTuples = pg_cmdtuples($rsltwgcontact);
			pg_close();
		}
	return $lNumTuples;
	}
}
?>