<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgcontactSet
//	Type                   :   Collection Class
//	Description            :   This class manages the collection of objects of class clswgcontact
//	Author                 :   NTCS Maintenance
//	Date                   :   11/01/2018
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($DOCUMENT_ROOT."classes/clswgcontact.php");
 
class clswgcontactSet
{ 
	var $awgcontact = array();
	function Add($obj)
	{
		$this->awgcontact[] = $obj;
	}
	function GetCount()
	{
		return count($this->awgcontact);
	}
	function GetItem($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgcontactSet:GetItem()";
			exit;
		}
		return $this->awgcontact[$lIndex];
	}
	function Remove($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgcontactSet:Remove()";
			exit;
		}
		for($i = $lIndex; $i < $lLastEntry; $i++)
		{
			$this->awgcontact[$i] = $this->awgcontact[$i+1];
		}
		array_pop($this->awgcontact);
	}
}
?>