<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgcareerManager
//	Type                   :   Manager Class
//	Description            :   This class implements the methods for DML operations of table wgcareer
//	Author                 :   NTCS Maintenance
//	Date                   :   12/01/2018
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($DOCUMENT_ROOT."classes/clswgcareer.php");
require_once($DOCUMENT_ROOT."classes/clswgcareerSet.php");
 
class clswgcareerManager
{
	function Savewgcareer($objwgcareer, $myConn=null)
	{
	
		$semail=$objwgcareer->getemail();
		$lmobnum=$objwgcareer->getmobnum();
		$sname=$objwgcareer->getname();
		$sresume=$objwgcareer->getresume();
		$swebsite=$objwgcareer->getwebsite();

		if($semail==null)
			$semail="' '";
		else
			$semail="'$semail'";

		if($lmobnum==null)
			$lmobnum="' '";;

		if($sname==null)
			$sname="' '";
		else
			$sname="'$sname'";

		if($sresume==null)
			$sresume="' '";
		else
			$sresume="'$sresume'";

		if($swebsite==null)
			$swebsite="' '";
		else
			$swebsite="'$swebsite'";
		$sQuery = "insert into wgcareer(email,mobnum,name,resume,website) values ($semail,$lmobnum,$sname,$sresume,$swebsite)";
        //echo $sQuery;
		@mysqli_close();
            global $DOCUMENT_ROOT;
            require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");
            //mysql_query($connection,$sQuery);
                     
            $rsltadded=0;
            if(mysqli_query($connection,$sQuery))
            {
                $rsltadded=1;
            }
            else
            {
                $rsltadded=2;
            }
             
            mysqli_close();
        return $rsltadded; 
	}
	function SavewgcareerSet($objwgcareerSet, $myConn=null)
	{
		$objwgcareer = new clswgcareer();
		$lNumRecord = $objwgcareerSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcareer = new clswgcareer();
				$objwgcareer = $objwgcareerSet->GetItem($lCount);
				
				$semail=$objwgcareer->getemail();
				$lmobnum=$objwgcareer->getmobnum();
				$sname=$objwgcareer->getname();
				$sresume=$objwgcareer->getresume();
				$swebsite=$objwgcareer->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($sresume==null)
					$sresume='null';
				else
					$sresume="'$sresume'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";
				$sQuery = "insert into wgcareer(email,mobnum,name,resume,website) values ($semail,$lmobnum,$sname,$sresume,$swebsite)";
				$rsltwgcareer = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcareerManager:SavewgcareerSet");
				$lNumTuples = pg_cmdtuples($rsltwgcareer);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
			}
			else
			{
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			pg_exec($connection,'begin');
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcareer = new clswgcareer();
				$objwgcareer = $objwgcareerSet->GetItem($lCount);
				
				$semail=$objwgcareer->getemail();
				$lmobnum=$objwgcareer->getmobnum();
				$sname=$objwgcareer->getname();
				$sresume=$objwgcareer->getresume();
				$swebsite=$objwgcareer->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($sresume==null)
					$sresume='null';
				else
					$sresume="'$sresume'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";
				$sQuery = "insert into wgcareer(email,mobnum,name,resume,website) values ($semail,$lmobnum,$sname,$sresume,$swebsite)";
				$rsltwgcareer = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcareerManager:SavewgcareerSet");
				$lNumTuples = pg_cmdtuples($rsltwgcareer);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
				pg_exec($connection,'commit');
				pg_close();
			}
			return $lTotalTuples;
	}

	function RetrievewgcareerSet($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgcareerSet = new clswgcareerSet();
		$rsltwgcareer = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcareerManager:Retrievewgcareer.");
		$lNumRows = pg_numrows($rsltwgcareer);
		if($lNumRows == 0)
		{
			pg_close();
			return $objwgcareerSet;
		}
		for($lCount = 0; $lCount < $lNumRows; $lCount++)
		{
			$objwgcareer = new clswgcareer();
			$arrwgcareer=pg_fetch_array($rsltwgcareer,$lCount);
			$objwgcareer->setemail($arrwgcareer[email]);
			$objwgcareer->setmobnum($arrwgcareer[mobnum]);
			$objwgcareer->setname($arrwgcareer[name]);
			$objwgcareer->setresume($arrwgcareer[resume]);
			$objwgcareer->setwebsite($arrwgcareer[website]);
			$objwgcareerSet->Add($objwgcareer);
		}
		pg_close();
		return $objwgcareerSet;
	}

	function Retrievewgcareer($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgcareer = new clswgcareer();
		$rsltwgcareer = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcareerManager:Retrievewgcareer.");
		$lNumRows = pg_numrows($rsltwgcareer);
		if($lNumRows == 0)
		{
			pg_close();
			return null;
		}
			$arrwgcareer=pg_fetch_array($rsltwgcareer,0);
			$objwgcareer->setemail($arrwgcareer[email]);
			$objwgcareer->setmobnum($arrwgcareer[mobnum]);
			$objwgcareer->setname($arrwgcareer[name]);
			$objwgcareer->setresume($arrwgcareer[resume]);
			$objwgcareer->setwebsite($arrwgcareer[website]);
		pg_close();
		return $objwgcareer;
	}

	function Updatewgcareer($objwgcareer, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$semail=$objwgcareer->getemail();
		$lmobnum=$objwgcareer->getmobnum();
		$sname=$objwgcareer->getname();
		$sresume=$objwgcareer->getresume();
		$swebsite=$objwgcareer->getwebsite();

		if($semail==null)
			$semail='null';
		else
			$semail="'$semail'";

		if($lmobnum==null)
			$lmobnum='null';

		if($sname==null)
			$sname='null';
		else
			$sname="'$sname'";

		if($sresume==null)
			$sresume='null';
		else
			$sresume="'$sresume'";

		if($swebsite==null)
			$swebsite='null';
		else
			$swebsite="'$swebsite'";

		$sQuery = "update wgcareer set
			email=$semail,
			mobnum=$lmobnum,
			resume=$sresume,
			website=$swebsite
			where name=$sname";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgcareer = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcareerManager:Updatewgcareer");
			$lNumTuples = pg_cmdtuples($rsltwgcareer);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgcareer = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcareerManager:Updatewgcareer");
			$lNumTuples = pg_cmdtuples($rsltwgcareer);
			pg_close();
		}
	return $lNumTuples;
	}
	function UpdatewgcareerSet($objwgcareerSet, $myConn=null)
	{
		$objwgcareer = new clswgcareer();
		$lNumRecord = $objwgcareerSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcareer = new clswgcareer();
				$objwgcareer = $objwgcareerSet->GetItem($lCount);
				
				$semail=$objwgcareer->getemail();
				$lmobnum=$objwgcareer->getmobnum();
				$sname=$objwgcareer->getname();
				$sresume=$objwgcareer->getresume();
				$swebsite=$objwgcareer->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($sresume==null)
					$sresume='null';
				else
					$sresume="'$sresume'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";

				$sQuery = "update wgcareer set
				email=$semail,
				mobnum=$lmobnum,
				resume=$sresume,
				website=$swebsite
				where name=$sname";
				$rsltwgcareer = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcareerManager:UpdatewgcareerSet");
				$lNumTuples = pg_cmdtuples($rsltwgcareer);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
			}
			else
			{
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			pg_exec($connection,'begin');
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgcareer = new clswgcareer();
				$objwgcareer = $objwgcareerSet->GetItem($lCount);
				
				$semail=$objwgcareer->getemail();
				$lmobnum=$objwgcareer->getmobnum();
				$sname=$objwgcareer->getname();
				$sresume=$objwgcareer->getresume();
				$swebsite=$objwgcareer->getwebsite();

				if($semail==null)
					$semail='null';
				else
					$semail="'$semail'";

				if($lmobnum==null)
					$lmobnum='null';

				if($sname==null)
					$sname='null';
				else
					$sname="'$sname'";

				if($sresume==null)
					$sresume='null';
				else
					$sresume="'$sresume'";

				if($swebsite==null)
					$swebsite='null';
				else
					$swebsite="'$swebsite'";
				$sQuery = "update wgcareer set
				email=$semail,
				mobnum=$lmobnum,
				resume=$sresume,
				website=$swebsite
				where name=$sname";
				$rsltwgcareer = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcareerManager:UpdatewgcareerSet");
				$lNumTuples = pg_cmdtuples($rsltwgcareer);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
				pg_exec($connection,'commit');
				pg_close();
			}
			return $lTotalTuples;
	}

	function Deletewgcareer($obj, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$sname=$obj->getname();

		if($sname==null)
			$sname='null';
		else
			$sname="'$sname'";
		$sQuery = "delete from wgcareer
			where name=$sname";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgcareer = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgcareerManager:Deletewgcareer");
			$lNumTuples = pg_cmdtuples($rsltwgcareer);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgcareer = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgcareerManager:Deletewgcareer");
			$lNumTuples = pg_cmdtuples($rsltwgcareer);
			pg_close();
		}
	return $lNumTuples;
	}
}
?>