<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgtutorialSet
//	Type                   :   Collection Class
//	Description            :   This class manages the collection of objects of class clswgtutorial
//	Author                 :   
//	Date                   :   28/12/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($_SERVER['DOCUMENT_ROOT']."/classes/clswgtutorial.php");
 
class clswgtutorialSet
{ 
	var $awgtutorial = array();
	function Add($obj)
	{
		$this->awgtutorial[] = $obj;
	}
	function GetCount()
	{
		return count($this->awgtutorial);
	}
	function GetItem($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgtutorialSet:GetItem()";
			exit;
		}
		return $this->awgtutorial[$lIndex];
	}
	function Remove($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgtutorialSet:Remove()";
			exit;
		}
		for($i = $lIndex; $i < $lLastEntry; $i++)
		{
			$this->awgtutorial[$i] = $this->awgtutorial[$i+1];
		}
		array_pop($this->awgtutorial);
	}
}
?>