<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgtutorialdiscimgSet
//	Type                   :   Collection Class
//	Description            :   This class manages the collection of objects of class clswgtutorialdiscimg
//	Author                 :   
//	Date                   :   29/12/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($_SERVER['DOCUMENT_ROOT']."/classes/clswgtutorialdiscimg.php");
 
class clswgtutorialdiscimgSet
{ 
	var $awgtutorialdiscimg = array();
	function Add($obj)
	{
		$this->awgtutorialdiscimg[] = $obj;
	}
	function GetCount()
	{
		return count($this->awgtutorialdiscimg);
	}
	function GetItem($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgtutorialdiscimgSet:GetItem()";
			exit;
		}
		return $this->awgtutorialdiscimg[$lIndex];
	}
	function Remove($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if($lIndex < 0 || $lIndex > $lLastEntry-1)
		{
			echo " MyError: Illegal index Passed to  clswgtutorialdiscimgSet:Remove()";
			exit;
		}
		for($i = $lIndex; $i < $lLastEntry; $i++)
		{
			$this->awgtutorialdiscimg[$i] = $this->awgtutorialdiscimg[$i+1];
		}
		array_pop($this->awgtutorialdiscimg);
	}
}
?>