<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgtutorialdiscimgManager
//	Type                   :   Manager Class
//	Description            :   This class implements the methods for DML operations of table wgtutorialdiscimg
//	Author                 :   
//	Date                   :   29/12/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($_SERVER['DOCUMENT_ROOT']."/classes/clswgtutorialdiscimg.php");
require_once($_SERVER['DOCUMENT_ROOT']."/classes/clswgtutorialdiscimgSet.php");
 
class clswgtutorialdiscimgManager
{
	function Savewgtutorialdiscimg($objwgtutorialdiscimg, $myConn=null)
	{
	
		$simagename=$objwgtutorialdiscimg->getimagename();
		$simgtitle=$objwgtutorialdiscimg->getimgtitle();
		$lsubtitleid=$objwgtutorialdiscimg->getsubtitleid();
		$ltitleid=$objwgtutorialdiscimg->gettitleid();
		$swgsubject=$objwgtutorialdiscimg->getwgsubject();

		if($simagename==null)
			$simagename="' '";
		else
			$simagename="'$simagename'";

		if($simgtitle==null)
			$simgtitle="' '";
		else
			$simgtitle="'$simgtitle'";

		if($lsubtitleid==null)
			$lsubtitleid="' '";

		if($ltitleid==null)
			$ltitleid="' '";

		if($swgsubject==null)
			$swgsubject="' '";
		else
			$swgsubject="'$swgsubject'";
		$sQuery = "insert into wgtutorialdiscimg(imagename,imgtitle,subtitleid,titleid,wgsubject) values ($simagename,$simgtitle,$lsubtitleid,$ltitleid,$swgsubject)";
		if(is_resource($myConn) and get_resource_type($myConn)== 'mysql link')
		{
			@mysqli_close();
            global $DOCUMENT_ROOT;
            require($DOCUMENT_ROOT."/dbconnect.php");  
            $rsltadded=0;
            if(mysqli_query($connection,$sQuery))
            {
                $rsltadded=1;
            }
            else
            {
                $rsltadded=2;
            }
            mysqli_close();
          return $rsltadded; 
		}
		else
		{
		@mysqli_close();
            global $DOCUMENT_ROOT;
            require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");  
            $rsltadded=0;
            if(mysqli_query($connection,$sQuery))
            {
                $rsltadded=1;
            }
            else
            {
                $rsltadded=2;
            }
            mysqli_close();
         return $rsltadded; 
		}
	}
	function SavewgtutorialdiscimgSet($objwgtutorialdiscimgSet, $myConn=null)
	{
		$objwgtutorialdiscimg = new clswgtutorialdiscimg();
		$lNumRecord = $objwgtutorialdiscimgSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'mysql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgtutorialdiscimg = new clswgtutorialdiscimg();
				$objwgtutorialdiscimg = $objwgtutorialdiscimgSet->GetItem($lCount);
				
					$simagename=$objwgtutorialdiscimg->getimagename();
		$simgtitle=$objwgtutorialdiscimg->getimgtitle();
		$lsubtitleid=$objwgtutorialdiscimg->getsubtitleid();
		$ltitleid=$objwgtutorialdiscimg->gettitleid();
		$swgsubject=$objwgtutorialdiscimg->getwgsubject();

		if($simagename==null)
			$simagename="' '";
		else
			$simagename="'$simagename'";

		if($simgtitle==null)
			$simgtitle="' '";
		else
			$simgtitle="'$simgtitle'";

		if($lsubtitleid==null)
			$lsubtitleid="' '";

		if($ltitleid==null)
			$ltitleid="' '";

		if($swgsubject==null)
			$swgsubject="' '";
		else
			$swgsubject="'$swgsubject'";
		$sQuery = "insert into wgtutorialdiscimg(imagename,imgtitle,subtitleid,titleid,wgsubject) values ($simagename,$simgtitle,$lsubtitleid,$ltitleid,$swgsubject)";
	       $rsltadded=0;
               	mysqli_query($myConn,'begin');
                global $DOCUMENT_ROOT;
                require($DOCUMENT_ROOT."/dbconnect.php");
                if(mysqli_query($myConn,$sQuery))
                {
                    $rsltadded=1;
                }
                else
                {
                    $rsltadded=2;
                }
                if($rsltadded ==1)
    			{
    				$lTotalTuples = $lTotalTuples + 1;
    			}
              }  
                if($lTotalTuples==$lNumRecord)
                {
    				mysqli_query($myConn,'commit');
    				mysql_close();
                }
                else
                {
                    mysqli_query($myConn,'rollback');
                    mysql_close();
                }   
			
            }
			else
			{
    			global $DOCUMENT_ROOT;
    			require($DOCUMENT_ROOT."/dbconnect.php");
    			mysqli_query($connection,'begin');
    			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
    			{
    				$objwgtutorialdiscimg = new clswgtutorialdiscimg();
    				$objwgtutorialdiscimg = $objwgtutorialdiscimgSet->GetItem($lCount);
    				
    				$simagename=$objwgtutorialdiscimg->getimagename();
    				$simgtitle=$objwgtutorialdiscimg->getimgtitle();
    				$lsubtitleid=$objwgtutorialdiscimg->getsubtitleid();
    				$ltitleid=$objwgtutorialdiscimg->gettitleid();
    				$swgsubject=$objwgtutorialdiscimg->getwgsubject();
    
    				if($simagename==null)
    					$simagename='null';
    				else
    					$simagename="'$simagename'";
    
    				if($simgtitle==null)
    					$simgtitle='null';
    				else
    					$simgtitle="'$simgtitle'";
    
    				if($lsubtitleid==null)
    					$lsubtitleid='null';
    
    				if($ltitleid==null)
    					$ltitleid='null';
    
    				if($swgsubject==null)
    					$swgsubject='null';
    				else
    					$swgsubject="'$swgsubject'";
    				$sQuery = "insert into wgtutorialdiscimg(imagename,imgtitle,subtitleid,titleid,wgsubject) values ($simagename,$simgtitle,$lsubtitleid,$ltitleid,$swgsubject)";
    				$rsltadded=0;
                    global $DOCUMENT_ROOT;
                    require($DOCUMENT_ROOT."/dbconnect.php");  
                    $rsltadded=0;
                    if(mysqli_query($connection,$sQuery))
                    {
                        $rsltadded=1;
                    }
                    else
                    {
                        $rsltadded=2;
                    }
                				if($rsltadded ==1)
                				{
                					$lTotalTuples = $lTotalTuples + 1;
                				}
     			}
                			if($lTotalTuples==$lNumRecord)
                            {
                				mysqli_query($connection,'commit');
                				mysql_close();
                            }
                            else
                            {
                                mysqli_query($connection,'rollback');
                                mysql_close();
                            }   
			}
			return $lTotalTuples;
	}

	function RetrievewgtutorialdiscimgSet($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgtutorialdiscimgSet = new clswgtutorialdiscimgSet();
		$rsltwgtutorialdiscimg = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:Retrievewgtutorialdiscimg.");
		$lNumRows = pg_numrows($rsltwgtutorialdiscimg);
		if($lNumRows == 0)
		{
			pg_close();
			return $objwgtutorialdiscimgSet;
		}
		for($lCount = 0; $lCount < $lNumRows; $lCount++)
		{
			$objwgtutorialdiscimg = new clswgtutorialdiscimg();
			$arrwgtutorialdiscimg=pg_fetch_array($rsltwgtutorialdiscimg,$lCount);
			$objwgtutorialdiscimg->setimagename($arrwgtutorialdiscimg[imagename]);
			$objwgtutorialdiscimg->setimgtitle($arrwgtutorialdiscimg[imgtitle]);
			$objwgtutorialdiscimg->setsubtitleid($arrwgtutorialdiscimg[subtitleid]);
			$objwgtutorialdiscimg->settitleid($arrwgtutorialdiscimg[titleid]);
			$objwgtutorialdiscimg->setwgsubject($arrwgtutorialdiscimg[wgsubject]);
			$objwgtutorialdiscimgSet->Add($objwgtutorialdiscimg);
		}
		pg_close();
		return $objwgtutorialdiscimgSet;
	}

	function Retrievewgtutorialdiscimg($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgtutorialdiscimg = new clswgtutorialdiscimg();
		$rsltwgtutorialdiscimg = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:Retrievewgtutorialdiscimg.");
		$lNumRows = pg_numrows($rsltwgtutorialdiscimg);
		if($lNumRows == 0)
		{
			pg_close();
			return null;
		}
			$arrwgtutorialdiscimg=pg_fetch_array($rsltwgtutorialdiscimg,0);
			$objwgtutorialdiscimg->setimagename($arrwgtutorialdiscimg[imagename]);
			$objwgtutorialdiscimg->setimgtitle($arrwgtutorialdiscimg[imgtitle]);
			$objwgtutorialdiscimg->setsubtitleid($arrwgtutorialdiscimg[subtitleid]);
			$objwgtutorialdiscimg->settitleid($arrwgtutorialdiscimg[titleid]);
			$objwgtutorialdiscimg->setwgsubject($arrwgtutorialdiscimg[wgsubject]);
		pg_close();
		return $objwgtutorialdiscimg;
	}

	function Updatewgtutorialdiscimg($objwgtutorialdiscimg, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$simagename=$objwgtutorialdiscimg->getimagename();
		$simgtitle=$objwgtutorialdiscimg->getimgtitle();
		$lsubtitleid=$objwgtutorialdiscimg->getsubtitleid();
		$ltitleid=$objwgtutorialdiscimg->gettitleid();
		$swgsubject=$objwgtutorialdiscimg->getwgsubject();

		if($simagename==null)
			$simagename='null';
		else
			$simagename="'$simagename'";

		if($simgtitle==null)
			$simgtitle='null';
		else
			$simgtitle="'$simgtitle'";

		if($lsubtitleid==null)
			$lsubtitleid='null';

		if($ltitleid==null)
			$ltitleid='null';

		if($swgsubject==null)
			$swgsubject='null';
		else
			$swgsubject="'$swgsubject'";

		$sQuery = "update wgtutorialdiscimg set
			imagename=$simagename,
			imgtitle=$simgtitle,
			titleid=$ltitleid,
			wgsubject=$swgsubject
			where subtitleid=$lsubtitleid";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgtutorialdiscimg = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:Updatewgtutorialdiscimg");
			$lNumTuples = pg_cmdtuples($rsltwgtutorialdiscimg);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgtutorialdiscimg = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:Updatewgtutorialdiscimg");
			$lNumTuples = pg_cmdtuples($rsltwgtutorialdiscimg);
			pg_close();
		}
	return $lNumTuples;
	}
	function UpdatewgtutorialdiscimgSet($objwgtutorialdiscimgSet, $myConn=null)
	{
		$objwgtutorialdiscimg = new clswgtutorialdiscimg();
		$lNumRecord = $objwgtutorialdiscimgSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgtutorialdiscimg = new clswgtutorialdiscimg();
				$objwgtutorialdiscimg = $objwgtutorialdiscimgSet->GetItem($lCount);
				
				$simagename=$objwgtutorialdiscimg->getimagename();
				$simgtitle=$objwgtutorialdiscimg->getimgtitle();
				$lsubtitleid=$objwgtutorialdiscimg->getsubtitleid();
				$ltitleid=$objwgtutorialdiscimg->gettitleid();
				$swgsubject=$objwgtutorialdiscimg->getwgsubject();

				if($simagename==null)
					$simagename='null';
				else
					$simagename="'$simagename'";

				if($simgtitle==null)
					$simgtitle='null';
				else
					$simgtitle="'$simgtitle'";

				if($lsubtitleid==null)
					$lsubtitleid='null';

				if($ltitleid==null)
					$ltitleid='null';

				if($swgsubject==null)
					$swgsubject='null';
				else
					$swgsubject="'$swgsubject'";

				$sQuery = "update wgtutorialdiscimg set
				imagename=$simagename,
				imgtitle=$simgtitle,
				titleid=$ltitleid,
				wgsubject=$swgsubject
				where subtitleid=$lsubtitleid";
				$rsltwgtutorialdiscimg = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:UpdatewgtutorialdiscimgSet");
				$lNumTuples = pg_cmdtuples($rsltwgtutorialdiscimg);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
			}
			else
			{
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			pg_exec($connection,'begin');
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgtutorialdiscimg = new clswgtutorialdiscimg();
				$objwgtutorialdiscimg = $objwgtutorialdiscimgSet->GetItem($lCount);
				
				$simagename=$objwgtutorialdiscimg->getimagename();
				$simgtitle=$objwgtutorialdiscimg->getimgtitle();
				$lsubtitleid=$objwgtutorialdiscimg->getsubtitleid();
				$ltitleid=$objwgtutorialdiscimg->gettitleid();
				$swgsubject=$objwgtutorialdiscimg->getwgsubject();

				if($simagename==null)
					$simagename='null';
				else
					$simagename="'$simagename'";

				if($simgtitle==null)
					$simgtitle='null';
				else
					$simgtitle="'$simgtitle'";

				if($lsubtitleid==null)
					$lsubtitleid='null';

				if($ltitleid==null)
					$ltitleid='null';

				if($swgsubject==null)
					$swgsubject='null';
				else
					$swgsubject="'$swgsubject'";
				$sQuery = "update wgtutorialdiscimg set
				imagename=$simagename,
				imgtitle=$simgtitle,
				titleid=$ltitleid,
				wgsubject=$swgsubject
				where subtitleid=$lsubtitleid";
				$rsltwgtutorialdiscimg = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:UpdatewgtutorialdiscimgSet");
				$lNumTuples = pg_cmdtuples($rsltwgtutorialdiscimg);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
				pg_exec($connection,'commit');
				pg_close();
			}
			return $lTotalTuples;
	}

	function Deletewgtutorialdiscimg($obj, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$lsubtitleid=$obj->getsubtitleid();

		if($lsubtitleid==null)
			$lsubtitleid='null';
		$sQuery = "delete from wgtutorialdiscimg
			where subtitleid=$lsubtitleid";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgtutorialdiscimg = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:Deletewgtutorialdiscimg");
			$lNumTuples = pg_cmdtuples($rsltwgtutorialdiscimg);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgtutorialdiscimg = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialdiscimgManager:Deletewgtutorialdiscimg");
			$lNumTuples = pg_cmdtuples($rsltwgtutorialdiscimg);
			pg_close();
		}
	return $lNumTuples;
	}
}
?>