<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgcontact
//	Type                   :   Entity Class
//	Description            :   This class contains Accessor and Mutator methods for each field of table wgcontact
//	Author                 :   NTCS Maintenance
//	Date                   :   11/01/2018
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

 
class clswgcontact
{
	var $tdiscription;
	var $semail;
	var $lmobnum;
	var $sname;
	var $ssubject;
	var $swebsite;


	function getdiscription()
	{
		return $this->tdiscription;
	}
	function setdiscription($Data)
	{
		$this->tdiscription = $Data;
	}

	function getemail()
	{
		return $this->semail;
	}
	function setemail($Data)
	{
		$this->semail = $Data;
	}

	function getmobnum()
	{
		return $this->lmobnum;
	}
	function setmobnum($Data)
	{
		$this->lmobnum = $Data;
	}

	function getname()
	{
		return $this->sname;
	}
	function setname($Data)
	{
		$this->sname = $Data;
	}

	function getsubject()
	{
		return $this->ssubject;
	}
	function setsubject($Data)
	{
		$this->ssubject = $Data;
	}

	function getwebsite()
	{
		return $this->swebsite;
	}
	function setwebsite($Data)
	{
		$this->swebsite = $Data;
	}

}
?>