<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgtutorialdiscimg
//	Type                   :   Entity Class
//	Description            :   This class contains Accessor and Mutator methods for each field of table wgtutorialdiscimg
//	Author                 :   
//	Date                   :   29/12/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

 
class clswgtutorialdiscimg
{
	var $simagename;
	var $simgtitle;
	var $lsubtitleid;
	var $ltitleid;
	var $swgsubject;


	function getimagename()
	{
		return $this->simagename;
	}
	function setimagename($Data)
	{
		$this->simagename = $Data;
	}

	function getimgtitle()
	{
		return $this->simgtitle;
	}
	function setimgtitle($Data)
	{
		$this->simgtitle = $Data;
	}

	function getsubtitleid()
	{
		return $this->lsubtitleid;
	}
	function setsubtitleid($Data)
	{
		$this->lsubtitleid = $Data;
	}

	function gettitleid()
	{
		return $this->ltitleid;
	}
	function settitleid($Data)
	{
		$this->ltitleid = $Data;
	}

	function getwgsubject()
	{
		return $this->swgsubject;
	}
	function setwgsubject($Data)
	{
		$this->swgsubject = $Data;
	}

}
?>