<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgtutorialManager
//	Type                   :   Manager Class
//	Description            :   This class implements the methods for DML operations of table wgtutorial
//	Author                 :   
//	Date                   :   28/12/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

require_once($_SERVER['DOCUMENT_ROOT']."/classes/clswgtutorial.php");
require_once($_SERVER['DOCUMENT_ROOT']."/classes/clswgtutorialSet.php");
 
class clswgtutorialManager
{
	function Savewgtutorial($objwgtutorial, $myConn=null)
	{
	
		$tdiscription=$objwgtutorial->getdiscription();
		$ssubtitle=$objwgtutorial->getsubtitle();
		$isubtitleid=$objwgtutorial->getsubtitleid();
		$ssubtitleone=$objwgtutorial->getsubtitleone();
		$lsubtitleoneid=$objwgtutorial->getsubtitleoneid();
		$ssubtitlethree=$objwgtutorial->getsubtitlethree();
		$lsubtitlethreeid=$objwgtutorial->getsubtitlethreeid();
		$ssubtitletwo=$objwgtutorial->getsubtitletwo();
		$lsubtitletwoid=$objwgtutorial->getsubtitletwoid();
		$ttextone=$objwgtutorial->gettextone();
		$ltextthree=$objwgtutorial->gettextthree();
		$ttexttwo=$objwgtutorial->gettexttwo();
		$stitle=$objwgtutorial->gettitle();
		$ltitleid=$objwgtutorial->gettitleid();
		$swgcategory=$objwgtutorial->getwgcategory();
		$swgsubcategory=$objwgtutorial->getwgsubcategory();
		$swgsubject=$objwgtutorial->getwgsubject();
		$twgtime=$objwgtutorial->getwgtime();
		$lwguserid=$objwgtutorial->getwguserid();
		$swgusertype=$objwgtutorial->getwgusertype();

       	if($tdiscription==null)
			$tdiscription="' '";
		else
			$tdiscription="'$tdiscription'";
            
  	     if($ttexttwo==null)
			$ttexttwo="' '";
		else
			$ttexttwo="'$ttexttwo'";
            
        if($ttextone==null)
			$ttextone="' '";
		else
			$ttextone="'$ttextone'";
            
            
		if($ssubtitle==null)
			$ssubtitle="' '";
		else
			$ssubtitle="'$ssubtitle'";

		if($isubtitleid==null)
			$isubtitleid="' '";

		if($ssubtitleone==null)
			$ssubtitleone="' '";
		else
			$ssubtitleone="'$ssubtitleone'";

		if($lsubtitleoneid==null)
			$lsubtitleoneid="' '";

		if($ssubtitlethree==null)
			$ssubtitlethree="' '";
		else
			$ssubtitlethree="'$ssubtitlethree'";

		if($lsubtitlethreeid==null)
			$lsubtitlethreeid="' '";

		if($ssubtitletwo==null)
			$ssubtitletwo="' '";
		else
			$ssubtitletwo="'$ssubtitletwo'";

		if($lsubtitletwoid==null)
			$lsubtitletwoid="' '";

		if($ltextthree==null)
			$ltextthree="' '";
        else
			$ltextthree="'$ltextthree'";

		if($stitle==null)
			$stitle="' '";
		else
			$stitle="'$stitle'";

		if($ltitleid==null)
			$ltitleid="' '";

		if($swgcategory==null)
			$swgcategory="' '";
		else
			$swgcategory="'$swgcategory'";

		if($swgsubcategory==null)
			$swgsubcategory="' '";
		else
			$swgsubcategory="'$swgsubcategory'";

		if($swgsubject==null)
			$swgsubject="' '";
		else
			$swgsubject="'$swgsubject'";

		if($lwguserid==null)
			$lwguserid="' '";

		if($swgusertype==null)
			$swgusertype=null;
		else
			$swgusertype="'$swgusertype'";
            
		$sQuery = "insert into wgtutorial(discription,subtitle,subtitleid,subtitleone,subtitleoneid,subtitlethree,subtitlethreeid,subtitletwo,subtitletwoid,textone,textthree,texttwo,title,titleid,wgcategory,wgsubcategory,wgsubject,wgtime,wguserid,wgusertype) values
         ($tdiscription,$ssubtitle,$isubtitleid,$ssubtitleone,$lsubtitleoneid,$ssubtitlethree,$lsubtitlethreeid,$ssubtitletwo,$lsubtitletwoid,$ttextone,$ltextthree,$ttexttwo,$stitle,$ltitleid,$swgcategory,$swgsubcategory,$swgsubject,CURRENT_TIMESTAMP,$lwguserid,$swgusertype)";
        @mysqli_close();
            global $DOCUMENT_ROOT;
            require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");
            //mysql_query($connection,$sQuery);
                     
            $rsltadded=0;
            if(mysqli_query($connection,$sQuery))
            {
                $rsltadded=1;
            }
            else
            {
                $rsltadded=2;
            }
             
            mysqli_close();
        return $rsltadded;    
	}
	function SavewgtutorialSet($objwgtutorialSet, $myConn=null)
	{
		$objwgtutorial = new clswgtutorial();
		$lNumRecord = $objwgtutorialSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
        				$objwgtutorial = new clswgtutorial();
        				$objwgtutorial = $objwgtutorialSet->GetItem($lCount);
                    $tdiscription=$objwgtutorial->getdiscription();
            		$ssubtitle=$objwgtutorial->getsubtitle();
            		$isubtitleid=$objwgtutorial->getsubtitleid();
            		$ssubtitleone=$objwgtutorial->getsubtitleone();
            		$lsubtitleoneid=$objwgtutorial->getsubtitleoneid();
            		$ssubtitlethree=$objwgtutorial->getsubtitlethree();
            		$lsubtitlethreeid=$objwgtutorial->getsubtitlethreeid();
            		$ssubtitletwo=$objwgtutorial->getsubtitletwo();
            		$lsubtitletwoid=$objwgtutorial->getsubtitletwoid();
            		$ttextone=$objwgtutorial->gettextone();
            		$ltextthree=$objwgtutorial->gettextthree();
            		$ttexttwo=$objwgtutorial->gettexttwo();
            		$stitle=$objwgtutorial->gettitle();
            		$ltitleid=$objwgtutorial->gettitleid();
            		$swgcategory=$objwgtutorial->getwgcategory();
            		$swgsubcategory=$objwgtutorial->getwgsubcategory();
            		$swgsubject=$objwgtutorial->getwgsubject();
            		$twgtime=$objwgtutorial->getwgtime();
            		$lwguserid=$objwgtutorial->getwguserid();
            		$swgusertype=$objwgtutorial->getwgusertype();
                    				
                        		if($tdiscription==null)
            			$tdiscription="' '";
            		else
            			$tdiscription="'$tdiscription'";
                        
              	     if($ttexttwo==null)
            			$ttexttwo="' '";
            		else
            			$ttexttwo="'$ttexttwo'";
                        
                    if($ttextone==null)
            			$ttextone="' '";
            		else
            			$ttextone="'$ttextone'";
                        
                        
            		if($ssubtitle==null)
            			$ssubtitle="' '";
            		else
            			$ssubtitle="'$ssubtitle'";
            
            		if($isubtitleid==null)
            			$isubtitleid="' '";
            
            		if($ssubtitleone==null)
            			$ssubtitleone="' '";
            		else
            			$ssubtitleone="'$ssubtitleone'";
            
            		if($lsubtitleoneid==null)
            			$lsubtitleoneid="' '";
            
            		if($ssubtitlethree==null)
            			$ssubtitlethree="' '";
            		else
            			$ssubtitlethree="'$ssubtitlethree'";
            
            		if($lsubtitlethreeid==null)
            			$lsubtitlethreeid="' '";
            
            		if($ssubtitletwo==null)
            			$ssubtitletwo="' '";
            		else
            			$ssubtitletwo="'$ssubtitletwo'";
            
            		if($lsubtitletwoid==null)
            			$lsubtitletwoid="' '";
            
            		if($ltextthree==null)
            			$ltextthree="' '";
                    else
            			$ltextthree="'$ltextthree'";
            
            		if($stitle==null)
            			$stitle="' '";
            		else
            			$stitle="'$stitle'";
            
            		if($ltitleid==null)
            			$ltitleid="' '";
            
            		if($swgcategory==null)
            			$swgcategory="' '";
            		else
            			$swgcategory="'$swgcategory'";
            
            		if($swgsubcategory==null)
            			$swgsubcategory="' '";
            		else
            			$swgsubcategory="'$swgsubcategory'";
            
            		if($swgsubject==null)
            			$swgsubject="' '";
            		else
            			$swgsubject="'$swgsubject'";
            
            		if($lwguserid==null)
            			$lwguserid="' '";
            
            		if($swgusertype==null)
            			$swgusertype=null;
            		else
            			$swgusertype="'$swgusertype'";
                        
            		$sQuery = "insert into wgtutorial(discription,subtitle,subtitleid,subtitleone,subtitleoneid,subtitlethree,subtitlethreeid,subtitletwo,subtitletwoid,textone,textthree,texttwo,title,titleid,wgcategory,wgsubcategory,wgsubject,wgtime,wguserid,wgusertype) values
                     ($tdiscription,$ssubtitle,$isubtitleid,$ssubtitleone,$lsubtitleoneid,$ssubtitlethree,$lsubtitlethreeid,$ssubtitletwo,$lsubtitletwoid,$ttextone,$ltextthree,$ttexttwo,$stitle,$ltitleid,$swgcategory,$swgsubcategory,$swgsubject,CURRENT_TIMESTAMP,$lwguserid,$swgusertype)";
                    mysqli($myConn,'begin');
                        global $DOCUMENT_ROOT;
                        require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");  
                        $rsltadded=0;
                        if(mysqli_query($connection,$sQuery))
                        {
                            $rsltadded=1;
                        }
                        else
                        {
                            $rsltadded=2;
                        }
        				if($rsltadded ==1)
        				{
        					$lTotalTuples = $lTotalTuples + 1;
        				}
                        if($lTotalTuples==$lNumRecord)
                        {
            				mysqli($myConn,'commit');
            				mysql_close();
                        }
                        else
                        {
                            mysqli($myConn,'rollback');
                            mysql_close();
                        }   
			     }
			}
			else
			{
        			global $DOCUMENT_ROOT;
        			require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");
        			mysqli_query($connection,'begin');
        			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
        			{
        				$objwgtutorial = new clswgtutorial();
        				$objwgtutorial = $objwgtutorialSet->GetItem($lCount);
        				
		            $tdiscription=$objwgtutorial->getdiscription();
            		$ssubtitle=$objwgtutorial->getsubtitle();
            		$isubtitleid=$objwgtutorial->getsubtitleid();
            		$ssubtitleone=$objwgtutorial->getsubtitleone();
            		$lsubtitleoneid=$objwgtutorial->getsubtitleoneid();
            		$ssubtitlethree=$objwgtutorial->getsubtitlethree();
            		$lsubtitlethreeid=$objwgtutorial->getsubtitlethreeid();
            		$ssubtitletwo=$objwgtutorial->getsubtitletwo();
            		$lsubtitletwoid=$objwgtutorial->getsubtitletwoid();
            		$ttextone=$objwgtutorial->gettextone();
            		$ltextthree=$objwgtutorial->gettextthree();
            		$ttexttwo=$objwgtutorial->gettexttwo();
            		$stitle=$objwgtutorial->gettitle();
            		$ltitleid=$objwgtutorial->gettitleid();
            		$swgcategory=$objwgtutorial->getwgcategory();
            		$swgsubcategory=$objwgtutorial->getwgsubcategory();
            		$swgsubject=$objwgtutorial->getwgsubject();
            		$twgtime=$objwgtutorial->getwgtime();
            		$lwguserid=$objwgtutorial->getwguserid();
            		$swgusertype=$objwgtutorial->getwgusertype();
                    				
            		if($tdiscription==null)
            			$tdiscription="' '";
            		else
            			$tdiscription="'$tdiscription'";
                        
              	     if($ttexttwo==null)
            			$ttexttwo="' '";
            		else
            			$ttexttwo="'$ttexttwo'";
                        
                    if($ttextone==null)
            			$ttextone="' '";
            		else
            			$ttextone="'$ttextone'";
                        
                        
            		if($ssubtitle==null)
            			$ssubtitle="' '";
            		else
            			$ssubtitle="'$ssubtitle'";
            
            		if($isubtitleid==null)
            			$isubtitleid="' '";
            
            		if($ssubtitleone==null)
            			$ssubtitleone="' '";
            		else
            			$ssubtitleone="'$ssubtitleone'";
            
            		if($lsubtitleoneid==null)
            			$lsubtitleoneid="' '";
            
            		if($ssubtitlethree==null)
            			$ssubtitlethree="' '";
            		else
            			$ssubtitlethree="'$ssubtitlethree'";
            
            		if($lsubtitlethreeid==null)
            			$lsubtitlethreeid="' '";
            
            		if($ssubtitletwo==null)
            			$ssubtitletwo="' '";
            		else
            			$ssubtitletwo="'$ssubtitletwo'";
            
            		if($lsubtitletwoid==null)
            			$lsubtitletwoid="' '";
            
            		if($ltextthree==null)
            			$ltextthree="' '";
                    else
            			$ltextthree="'$ltextthree'";
            
            		if($stitle==null)
            			$stitle="' '";
            		else
            			$stitle="'$stitle'";
            
            		if($ltitleid==null)
            			$ltitleid="' '";
            
            		if($swgcategory==null)
            			$swgcategory="' '";
            		else
            			$swgcategory="'$swgcategory'";
            
            		if($swgsubcategory==null)
            			$swgsubcategory="' '";
            		else
            			$swgsubcategory="'$swgsubcategory'";
            
            		if($swgsubject==null)
            			$swgsubject="' '";
            		else
            			$swgsubject="'$swgsubject'";
            
            		if($lwguserid==null)
            			$lwguserid="' '";
            
            		if($swgusertype==null)
            			$swgusertype=null;
            		else
            			$swgusertype="'$swgusertype'";
                        
            		$sQuery = "insert into wgtutorial(discription,subtitle,subtitleid,subtitleone,subtitleoneid,subtitlethree,subtitlethreeid,subtitletwo,subtitletwoid,textone,textthree,texttwo,title,titleid,wgcategory,wgsubcategory,wgsubject,wgtime,wguserid,wgusertype) values
                     ($tdiscription,$ssubtitle,$isubtitleid,$ssubtitleone,$lsubtitleoneid,$ssubtitlethree,$lsubtitlethreeid,$ssubtitletwo,$lsubtitletwoid,$ttextone,$ltextthree,$ttexttwo,$stitle,$ltitleid,$swgcategory,$swgsubcategory,$swgsubject,CURRENT_TIMESTAMP,$lwguserid,$swgusertype)";
            		echo $sQuery;
                     $rsltadded=0;
                        if(mysqli_query($connection,$sQuery))
                        {
                            $rsltadded=1;
                        }
                        else
                        {
                            $rsltadded=2;
                        }
            				if($rsltadded ==1)
            				{
            					$lTotalTuples = $lTotalTuples + 1;
            				}
            			}
            			if($lTotalTuples==$lNumRecord)
                        {
            				mysqli($connection,'commit');
            				mysql_close();
                        }
                        else
                        {
                            mysqli($connection,'rollback');
                            mysql_close();
                        }   
			}
			return $lTotalTuples;
	}

	function RetrievewgtutorialSet($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/dbconnect.php");

		$objwgtutorialSet = new clswgtutorialSet();
		$rsltwgtutorial = mysqli_query($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:Retrievewgtutorial.");
		$lNumRows = mysqli_num_rows($rsltwgtutorial);
		if($lNumRows == 0)
		{
			pg_close();
			return $objwgtutorialSet;
		}
		for($lCount = 0; $lCount < $lNumRows; $lCount++)
		{
			$objwgtutorial = new clswgtutorial();
			$arrwgtutorial=pg_fetch_array($rsltwgtutorial,MYSQL_ASSOC);
			$objwgtutorial->setdiscription($arrwgtutorial[discription]);
			$objwgtutorial->setsubtitle($arrwgtutorial[subtitle]);
			$objwgtutorial->setsubtitleid($arrwgtutorial[subtitleid]);
			$objwgtutorial->setsubtitleone($arrwgtutorial[subtitleone]);
			$objwgtutorial->setsubtitleoneid($arrwgtutorial[subtitleoneid]);
			$objwgtutorial->setsubtitlethree($arrwgtutorial[subtitlethree]);
			$objwgtutorial->setsubtitlethreeid($arrwgtutorial[subtitlethreeid]);
			$objwgtutorial->setsubtitletwo($arrwgtutorial[subtitletwo]);
			$objwgtutorial->setsubtitletwoid($arrwgtutorial[subtitletwoid]);
			$objwgtutorial->settextone($arrwgtutorial[textone]);
			$objwgtutorial->settextthree($arrwgtutorial[textthree]);
			$objwgtutorial->settexttwo($arrwgtutorial[texttwo]);
			$objwgtutorial->settitle($arrwgtutorial[title]);
			$objwgtutorial->settitleid($arrwgtutorial[titleid]);
			$objwgtutorial->setwgcategory($arrwgtutorial[wgcategory]);
			$objwgtutorial->setwgsubcategory($arrwgtutorial[wgsubcategory]);
			$objwgtutorial->setwgsubject($arrwgtutorial[wgsubject]);
			$objwgtutorial->setwgtime($arrwgtutorial[wgtime]);
			$objwgtutorial->setwguserid($arrwgtutorial[wguserid]);
			$objwgtutorial->setwgusertype($arrwgtutorial[wgusertype]);
			$objwgtutorialSet->Add($objwgtutorial);
		}
		pg_close();
		return $objwgtutorialSet;
	}

	function Retrievewgtutorial($sQuery)
	{
		global $DOCUMENT_ROOT;

		require($DOCUMENT_ROOT."/ois/dbconnect.php");

		$objwgtutorial = new clswgtutorial();
		$rsltwgtutorial = mysqli_query($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:Retrievewgtutorial.");
		$lNumRows = mysqli_num_rows($rsltwgtutorial);
		if($lNumRows == 0)
		{
			pg_close();
			return null;
		}
			$arrwgtutorial=pg_fetch_array($rsltwgtutorial,0);
			$objwgtutorial->setdiscription($arrwgtutorial[discription]);
			$objwgtutorial->setsubtitle($arrwgtutorial[subtitle]);
			$objwgtutorial->setsubtitleid($arrwgtutorial[subtitleid]);
			$objwgtutorial->setsubtitleone($arrwgtutorial[subtitleone]);
			$objwgtutorial->setsubtitleoneid($arrwgtutorial[subtitleoneid]);
			$objwgtutorial->setsubtitlethree($arrwgtutorial[subtitlethree]);
			$objwgtutorial->setsubtitlethreeid($arrwgtutorial[subtitlethreeid]);
			$objwgtutorial->setsubtitletwo($arrwgtutorial[subtitletwo]);
			$objwgtutorial->setsubtitletwoid($arrwgtutorial[subtitletwoid]);
			$objwgtutorial->settextone($arrwgtutorial[textone]);
			$objwgtutorial->settextthree($arrwgtutorial[textthree]);
			$objwgtutorial->settexttwo($arrwgtutorial[texttwo]);
			$objwgtutorial->settitle($arrwgtutorial[title]);
			$objwgtutorial->settitleid($arrwgtutorial[titleid]);
			$objwgtutorial->setwgcategory($arrwgtutorial[wgcategory]);
			$objwgtutorial->setwgsubcategory($arrwgtutorial[wgsubcategory]);
			$objwgtutorial->setwgsubject($arrwgtutorial[wgsubject]);
			$objwgtutorial->setwgtime($arrwgtutorial[wgtime]);
			$objwgtutorial->setwguserid($arrwgtutorial[wguserid]);
			$objwgtutorial->setwgusertype($arrwgtutorial[wgusertype]);
		pg_close();
		return $objwgtutorial;
	}

	function Updatewgtutorial($objwgtutorial, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$tdiscription=$objwgtutorial->getdiscription();
		$ssubtitle=$objwgtutorial->getsubtitle();
		$isubtitleid=$objwgtutorial->getsubtitleid();
		$ssubtitleone=$objwgtutorial->getsubtitleone();
		$lsubtitleoneid=$objwgtutorial->getsubtitleoneid();
		$ssubtitlethree=$objwgtutorial->getsubtitlethree();
		$lsubtitlethreeid=$objwgtutorial->getsubtitlethreeid();
		$ssubtitletwo=$objwgtutorial->getsubtitletwo();
		$lsubtitletwoid=$objwgtutorial->getsubtitletwoid();
		$ttextone=$objwgtutorial->gettextone();
		$ltextthree=$objwgtutorial->gettextthree();
		$ttexttwo=$objwgtutorial->gettexttwo();
		$stitle=$objwgtutorial->gettitle();
		$ltitleid=$objwgtutorial->gettitleid();
		$swgcategory=$objwgtutorial->getwgcategory();
		$swgsubcategory=$objwgtutorial->getwgsubcategory();
		$swgsubject=$objwgtutorial->getwgsubject();
		$twgtime=$objwgtutorial->getwgtime();
		$lwguserid=$objwgtutorial->getwguserid();
		$swgusertype=$objwgtutorial->getwgusertype();

		if($ssubtitle==null)
			$ssubtitle='null';
		else
			$ssubtitle="'$ssubtitle'";

		if($isubtitleid==null)
			$isubtitleid='null';

		if($ssubtitleone==null)
			$ssubtitleone='null';
		else
			$ssubtitleone="'$ssubtitleone'";

		if($lsubtitleoneid==null)
			$lsubtitleoneid='null';

		if($ssubtitlethree==null)
			$ssubtitlethree='null';
		else
			$ssubtitlethree="'$ssubtitlethree'";

		if($lsubtitlethreeid==null)
			$lsubtitlethreeid='null';

		if($ssubtitletwo==null)
			$ssubtitletwo='null';
		else
			$ssubtitletwo="'$ssubtitletwo'";

		if($lsubtitletwoid==null)
			$lsubtitletwoid='null';

		if($ltextthree==null)
			$ltextthree='null';

		if($stitle==null)
			$stitle='null';
		else
			$stitle="'$stitle'";

		if($ltitleid==null)
			$ltitleid='null';

		if($swgcategory==null)
			$swgcategory='null';
		else
			$swgcategory="'$swgcategory'";

		if($swgsubcategory==null)
			$swgsubcategory='null';
		else
			$swgsubcategory="'$swgsubcategory'";

		if($swgsubject==null)
			$swgsubject='null';
		else
			$swgsubject="'$swgsubject'";

		if($lwguserid==null)
			$lwguserid='null';

		if($swgusertype==null)
			$swgusertype='null';
		else
			$swgusertype="'$swgusertype'";

		$sQuery = "update wgtutorial set
			discription=CURRENT_TIMESTAMP,
			subtitle=$ssubtitle,
			subtitleid=$isubtitleid,
			subtitleone=$ssubtitleone,
			subtitleoneid=$lsubtitleoneid,
			subtitlethree=$ssubtitlethree,
			subtitlethreeid=$lsubtitlethreeid,
			subtitletwo=$ssubtitletwo,
			subtitletwoid=$lsubtitletwoid,
			textone=CURRENT_TIMESTAMP,
			textthree=$ltextthree,
			texttwo=CURRENT_TIMESTAMP,
			title=$stitle,
			wgcategory=$swgcategory,
			wgsubcategory=$swgsubcategory,
			wgsubject=$swgsubject,
			wgtime=CURRENT_TIMESTAMP,
			wguserid=$lwguserid,
			wgusertype=$swgusertype
			where titleid=$ltitleid";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgtutorial = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:Updatewgtutorial");
			$lNumTuples = pg_cmdtuples($rsltwgtutorial);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgtutorial = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:Updatewgtutorial");
			$lNumTuples = pg_cmdtuples($rsltwgtutorial);
			pg_close();
		}
	return $lNumTuples;
	}
	function UpdatewgtutorialSet($objwgtutorialSet, $myConn=null)
	{
		$objwgtutorial = new clswgtutorial();
		$lNumRecord = $objwgtutorialSet->GetCount();
		$lTotalTuples = 0;
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgtutorial = new clswgtutorial();
				$objwgtutorial = $objwgtutorialSet->GetItem($lCount);
				
				$tdiscription=$objwgtutorial->getdiscription();
				$ssubtitle=$objwgtutorial->getsubtitle();
				$isubtitleid=$objwgtutorial->getsubtitleid();
				$ssubtitleone=$objwgtutorial->getsubtitleone();
				$lsubtitleoneid=$objwgtutorial->getsubtitleoneid();
				$ssubtitlethree=$objwgtutorial->getsubtitlethree();
				$lsubtitlethreeid=$objwgtutorial->getsubtitlethreeid();
				$ssubtitletwo=$objwgtutorial->getsubtitletwo();
				$lsubtitletwoid=$objwgtutorial->getsubtitletwoid();
				$ttextone=$objwgtutorial->gettextone();
				$ltextthree=$objwgtutorial->gettextthree();
				$ttexttwo=$objwgtutorial->gettexttwo();
				$stitle=$objwgtutorial->gettitle();
				$ltitleid=$objwgtutorial->gettitleid();
				$swgcategory=$objwgtutorial->getwgcategory();
				$swgsubcategory=$objwgtutorial->getwgsubcategory();
				$swgsubject=$objwgtutorial->getwgsubject();
				$twgtime=$objwgtutorial->getwgtime();
				$lwguserid=$objwgtutorial->getwguserid();
				$swgusertype=$objwgtutorial->getwgusertype();

				if($ssubtitle==null)
					$ssubtitle='null';
				else
					$ssubtitle="'$ssubtitle'";

				if($isubtitleid==null)
					$isubtitleid='null';

				if($ssubtitleone==null)
					$ssubtitleone='null';
				else
					$ssubtitleone="'$ssubtitleone'";

				if($lsubtitleoneid==null)
					$lsubtitleoneid='null';

				if($ssubtitlethree==null)
					$ssubtitlethree='null';
				else
					$ssubtitlethree="'$ssubtitlethree'";

				if($lsubtitlethreeid==null)
					$lsubtitlethreeid='null';

				if($ssubtitletwo==null)
					$ssubtitletwo='null';
				else
					$ssubtitletwo="'$ssubtitletwo'";

				if($lsubtitletwoid==null)
					$lsubtitletwoid='null';

				if($ltextthree==null)
					$ltextthree='null';

				if($stitle==null)
					$stitle='null';
				else
					$stitle="'$stitle'";

				if($ltitleid==null)
					$ltitleid='null';

				if($swgcategory==null)
					$swgcategory='null';
				else
					$swgcategory="'$swgcategory'";

				if($swgsubcategory==null)
					$swgsubcategory='null';
				else
					$swgsubcategory="'$swgsubcategory'";

				if($swgsubject==null)
					$swgsubject='null';
				else
					$swgsubject="'$swgsubject'";

				if($lwguserid==null)
					$lwguserid='null';

				if($swgusertype==null)
					$swgusertype='null';
				else
					$swgusertype="'$swgusertype'";

				$sQuery = "update wgtutorial set
				discription=CURRENT_TIMESTAMP,
				subtitle=$ssubtitle,
				subtitleid=$isubtitleid,
				subtitleone=$ssubtitleone,
				subtitleoneid=$lsubtitleoneid,
				subtitlethree=$ssubtitlethree,
				subtitlethreeid=$lsubtitlethreeid,
				subtitletwo=$ssubtitletwo,
				subtitletwoid=$lsubtitletwoid,
				textone=CURRENT_TIMESTAMP,
				textthree=$ltextthree,
				texttwo=CURRENT_TIMESTAMP,
				title=$stitle,
				wgcategory=$swgcategory,
				wgsubcategory=$swgsubcategory,
				wgsubject=$swgsubject,
				wgtime=CURRENT_TIMESTAMP,
				wguserid=$lwguserid,
				wgusertype=$swgusertype
				where titleid=$ltitleid";
				$rsltwgtutorial = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:UpdatewgtutorialSet");
				$lNumTuples = pg_cmdtuples($rsltwgtutorial);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
			}
			else
			{
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			pg_exec($connection,'begin');
			for($lCount = 0; $lCount < $lNumRecord; $lCount++)
			{
				$objwgtutorial = new clswgtutorial();
				$objwgtutorial = $objwgtutorialSet->GetItem($lCount);
				
				$tdiscription=$objwgtutorial->getdiscription();
				$ssubtitle=$objwgtutorial->getsubtitle();
				$isubtitleid=$objwgtutorial->getsubtitleid();
				$ssubtitleone=$objwgtutorial->getsubtitleone();
				$lsubtitleoneid=$objwgtutorial->getsubtitleoneid();
				$ssubtitlethree=$objwgtutorial->getsubtitlethree();
				$lsubtitlethreeid=$objwgtutorial->getsubtitlethreeid();
				$ssubtitletwo=$objwgtutorial->getsubtitletwo();
				$lsubtitletwoid=$objwgtutorial->getsubtitletwoid();
				$ttextone=$objwgtutorial->gettextone();
				$ltextthree=$objwgtutorial->gettextthree();
				$ttexttwo=$objwgtutorial->gettexttwo();
				$stitle=$objwgtutorial->gettitle();
				$ltitleid=$objwgtutorial->gettitleid();
				$swgcategory=$objwgtutorial->getwgcategory();
				$swgsubcategory=$objwgtutorial->getwgsubcategory();
				$swgsubject=$objwgtutorial->getwgsubject();
				$twgtime=$objwgtutorial->getwgtime();
				$lwguserid=$objwgtutorial->getwguserid();
				$swgusertype=$objwgtutorial->getwgusertype();

				if($ssubtitle==null)
					$ssubtitle='null';
				else
					$ssubtitle="'$ssubtitle'";

				if($isubtitleid==null)
					$isubtitleid='null';

				if($ssubtitleone==null)
					$ssubtitleone='null';
				else
					$ssubtitleone="'$ssubtitleone'";

				if($lsubtitleoneid==null)
					$lsubtitleoneid='null';

				if($ssubtitlethree==null)
					$ssubtitlethree='null';
				else
					$ssubtitlethree="'$ssubtitlethree'";

				if($lsubtitlethreeid==null)
					$lsubtitlethreeid='null';

				if($ssubtitletwo==null)
					$ssubtitletwo='null';
				else
					$ssubtitletwo="'$ssubtitletwo'";

				if($lsubtitletwoid==null)
					$lsubtitletwoid='null';

				if($ltextthree==null)
					$ltextthree='null';

				if($stitle==null)
					$stitle='null';
				else
					$stitle="'$stitle'";

				if($ltitleid==null)
					$ltitleid='null';

				if($swgcategory==null)
					$swgcategory='null';
				else
					$swgcategory="'$swgcategory'";

				if($swgsubcategory==null)
					$swgsubcategory='null';
				else
					$swgsubcategory="'$swgsubcategory'";

				if($swgsubject==null)
					$swgsubject='null';
				else
					$swgsubject="'$swgsubject'";

				if($lwguserid==null)
					$lwguserid='null';

				if($swgusertype==null)
					$swgusertype='null';
				else
					$swgusertype="'$swgusertype'";
				$sQuery = "update wgtutorial set
				discription=CURRENT_TIMESTAMP,
				subtitle=$ssubtitle,
				subtitleid=$isubtitleid,
				subtitleone=$ssubtitleone,
				subtitleoneid=$lsubtitleoneid,
				subtitlethree=$ssubtitlethree,
				subtitlethreeid=$lsubtitlethreeid,
				subtitletwo=$ssubtitletwo,
				subtitletwoid=$lsubtitletwoid,
				textone=CURRENT_TIMESTAMP,
				textthree=$ltextthree,
				texttwo=CURRENT_TIMESTAMP,
				title=$stitle,
				wgcategory=$swgcategory,
				wgsubcategory=$swgsubcategory,
				wgsubject=$swgsubject,
				wgtime=CURRENT_TIMESTAMP,
				wguserid=$lwguserid,
				wgusertype=$swgusertype
				where titleid=$ltitleid";
				$rsltwgtutorial = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:UpdatewgtutorialSet");
				$lNumTuples = pg_cmdtuples($rsltwgtutorial);
				if($lNumTuples !=0)
				{
					$lTotalTuples = $lTotalTuples + 1;
				}
			}
				pg_exec($connection,'commit');
				pg_close();
			}
			return $lTotalTuples;
	}

	function Deletewgtutorial($obj, $myConn=null)
	{
		global $DOCUMENT_ROOT;

	
		$ltitleid=$obj->gettitleid();

		if($ltitleid==null)
			$ltitleid='null';
		$sQuery = "delete from wgtutorial
			where titleid=$ltitleid";
		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')
		{
			$rsltwgtutorial = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:Deletewgtutorial");
			$lNumTuples = pg_cmdtuples($rsltwgtutorial);
		}
		else
		{
			@pg_close();
			global $DOCUMENT_ROOT;
			require($DOCUMENT_ROOT."/ois/dbconnect.php");
			$rsltwgtutorial = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clswgtutorialManager:Deletewgtutorial");
			$lNumTuples = pg_cmdtuples($rsltwgtutorial);
			pg_close();
		}
	return $lNumTuples;
	}
}
?>