<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgcareer
//	Type                   :   Entity Class
//	Description            :   This class contains Accessor and Mutator methods for each field of table wgcareer
//	Author                 :   NTCS Maintenance
//	Date                   :   12/01/2018
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

 
class clswgcareer
{
	var $semail;
	var $lmobnum;
	var $sname;
	var $sresume;
	var $swebsite;


	function getemail()
	{
		return $this->semail;
	}
	function setemail($Data)
	{
		$this->semail = $Data;
	}

	function getmobnum()
	{
		return $this->lmobnum;
	}
	function setmobnum($Data)
	{
		$this->lmobnum = $Data;
	}

	function getname()
	{
		return $this->sname;
	}
	function setname($Data)
	{
		$this->sname = $Data;
	}

	function getresume()
	{
		return $this->sresume;
	}
	function setresume($Data)
	{
		$this->sresume = $Data;
	}

	function getwebsite()
	{
		return $this->swebsite;
	}
	function setwebsite($Data)
	{
		$this->swebsite = $Data;
	}

}
?>