<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clswgtutorial
//	Type                   :   Entity Class
//	Description            :   This class contains Accessor and Mutator methods for each field of table wgtutorial
//	Author                 :   
//	Date                   :   28/12/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

 
class clswgtutorial
{
	var $tdiscription;
	var $ssubtitle;
	var $isubtitleid;
	var $ssubtitleone;
	var $lsubtitleoneid;
	var $ssubtitlethree;
	var $lsubtitlethreeid;
	var $ssubtitletwo;
	var $lsubtitletwoid;
	var $ttextone;
	var $ltextthree;
	var $ttexttwo;
	var $stitle;
	var $ltitleid;
	var $swgcategory;
	var $swgsubcategory;
	var $swgsubject;
	var $twgtime;
	var $lwguserid;
	var $swgusertype;


	function getdiscription()
	{
		return $this->tdiscription;
	}
	function setdiscription($Data)
	{
		$this->tdiscription = $Data;
	}

	function getsubtitle()
	{
		return $this->ssubtitle;
	}
	function setsubtitle($Data)
	{
		$this->ssubtitle = $Data;
	}

	function getsubtitleid()
	{
		return $this->isubtitleid;
	}
	function setsubtitleid($Data)
	{
		$this->isubtitleid = $Data;
	}

	function getsubtitleone()
	{
		return $this->ssubtitleone;
	}
	function setsubtitleone($Data)
	{
		$this->ssubtitleone = $Data;
	}

	function getsubtitleoneid()
	{
		return $this->lsubtitleoneid;
	}
	function setsubtitleoneid($Data)
	{
		$this->lsubtitleoneid = $Data;
	}

	function getsubtitlethree()
	{
		return $this->ssubtitlethree;
	}
	function setsubtitlethree($Data)
	{
		$this->ssubtitlethree = $Data;
	}

	function getsubtitlethreeid()
	{
		return $this->lsubtitlethreeid;
	}
	function setsubtitlethreeid($Data)
	{
		$this->lsubtitlethreeid = $Data;
	}

	function getsubtitletwo()
	{
		return $this->ssubtitletwo;
	}
	function setsubtitletwo($Data)
	{
		$this->ssubtitletwo = $Data;
	}

	function getsubtitletwoid()
	{
		return $this->lsubtitletwoid;
	}
	function setsubtitletwoid($Data)
	{
		$this->lsubtitletwoid = $Data;
	}

	function gettextone()
	{
		return $this->ttextone;
	}
	function settextone($Data)
	{
		$this->ttextone = $Data;
	}

	function gettextthree()
	{
		return $this->ltextthree;
	}
	function settextthree($Data)
	{
		$this->ltextthree = $Data;
	}

	function gettexttwo()
	{
		return $this->ttexttwo;
	}
	function settexttwo($Data)
	{
		$this->ttexttwo = $Data;
	}

	function gettitle()
	{
		return $this->stitle;
	}
	function settitle($Data)
	{
		$this->stitle = $Data;
	}

	function gettitleid()
	{
		return $this->ltitleid;
	}
	function settitleid($Data)
	{
		$this->ltitleid = $Data;
	}

	function getwgcategory()
	{
		return $this->swgcategory;
	}
	function setwgcategory($Data)
	{
		$this->swgcategory = $Data;
	}

	function getwgsubcategory()
	{
		return $this->swgsubcategory;
	}
	function setwgsubcategory($Data)
	{
		$this->swgsubcategory = $Data;
	}

	function getwgsubject()
	{
		return $this->swgsubject;
	}
	function setwgsubject($Data)
	{
		$this->swgsubject = $Data;
	}

	function getwgtime()
	{
		return $this->twgtime;
	}
	function setwgtime($Data)
	{
		$this->twgtime = $Data;
	}

	function getwguserid()
	{
		return $this->lwguserid;
	}
	function setwguserid($Data)
	{
		$this->lwguserid = $Data;
	}

	function getwgusertype()
	{
		return $this->swgusertype;
	}
	function setwgusertype($Data)
	{
		$this->swgusertype = $Data;
	}

}
?>