<?php
//   This class is generated by Class Automation System
//	Class Name             :   clsStudentDetailSet
//	Type                   :   Collection Class
//	Description            :   This class manages the collection of objects of class clsStudentDetailSet
//	Author                 :   Ashutosh Kumar Choubey
//	Date                   :   04/09/2017
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:  

class clsWGSubjectSet
{
    var $arrWGSubject = Array();
    function Add($obj)
    {
        $this->arrWGSubject[] = $obj;
    }
        
    function GetCount()
    {
        return count($this->arrWGSubject);
    }
        
    function GetItem($index)
    {
        $lLastEntry = $this->GetCount();
            
        if($index < 0 || $index > $lLastEntry-1)
        {
            echo " MyError: Illegal index Passed to  $arrWGSubject:GetItem()";
            exit;
        }
        return $this->arrWGSubject[$index];
    }
} 
?>