<?php
//   This class is generated by Class Automation System
//	Class Name             :  
//	Type                   :   
//	Description            :  
//	Author                 :  
//	Date                   :   
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   
class clsWGSubCategory
{
  
      var   $iWGSubCategoryID;
      var   $sWGSubCategoryName;                 
      
      function getWGSubCategoryID()
      {
        return $this->iWGSubCategoryID;
      }
      function setWGSubCategoryID($Data)
      {
        $this->iWGSubCategoryID= $Data;     
      }    
       
      function getWGSubCategoryName()
      {
        return $this->sWGSubCategoryName;
      }
      function setWGSubCategoryName($Data)
      {
        $this->sWGSubCategoryName = $Data;     
      }         
       
}
?>