<?php
//   This class is generated by Class Automation System
//	Class Name             :  
//	Type                   :   
//	Description            :  
//	Author                 :  
//	Date                   :   
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   
class clsWGAddTutorial
{
  
      var   $iWGUserId;
      var   $sWGUserType;        
      var   $sWGCategory;         
      var   $sWGSubCategory;         
      var   $sWGSubject;         
      var   $sWGTitle;            
      var   $sWGDiscription;              
      var   $sWGFileName;      
      var   $sWGFileType;         
      var   $sWGSubTitle;
      var   $dtWGtime;
      
      function getWGUserId()
      {
        return $this->iWGUserId;
      }
      function setWGUserId($Data)
      {
        $this->iWGUserId= $Data;     
      }    
       
      function getWGUserType()
      {
        return $this->sWGUserType;
      }
      function setWGUserType($Data)
      {
        $this->sWGUserType = $Data;     
      }         
   
      function getWGCategory()
      {
        return $this->sWGCategory;
      }
      function setWGCategory($Data)
      {
        $this->sWGCategory = $Data;     
      } 
           
      function getWGSubCategory()
      {
        return $this->sWGSubCategory;
      }
      function setWGSubCategory($Data)
      {
        $this->sWGSubCategory = $Data;     
      }
           
      function getWGSubject()
      {
        return $this->sWGSubject;
      }
      function setWGSubject($Data)
      {
        $this->sWGSubject = $Data;     
      } 
          
      function getWGTitle()
      {
        return $this->sWGTitle;
      }
      function setWGTitle($Data)
      {
         $this->sWGTitle = $Data;     
      }  
         
      function getWGDiscription()
      {
         return $this->sWGDiscription;
      }
      function setWGDiscription($Data)
      {
         $this->sWGDiscription = $Data;     
      }  
         
      function getWGFileName()
      {
        return $this->sWGFileName;
      }
      function setWGFileName($Data)
      {
        $this->sWGFileName = $Data;     
      }  
         
      function getWGFileType()
      {
        return $this->sWGFileType;
      }
      function setWGFileType($Data)
      {
        $this->sWGFileType = $Data;     
      } 
      function getWGSubTitle()
      {
        return $this->sWGSubTitle;
      }
      function setWGSubTitle($Data)
      {
        $this->sWGSubTitle = $Data;     
      } 
      function getWGtime()
      {
        return $this->dtWGtime;
      }
      function setWGtime($Data)
      {
        $this->dtWGtime = $Data;     
      } 
       
}
?>