<?php
//   This class is generated by Class Automation System
//	Class Name             :  
//	Type                   :   
//	Description            :  
//	Author                 :  
//	Date                   :   
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   
class clsWGSubject
{
  
      var   $iWGSubjectId;
      var   $sWGSubjectName; 
      var   $sWGCategory;
      var   $sWGSubCategory;       
      
      function getWGSubjectId()
      {
        return $this->iWGSubjectId;
      }
      function setWGSubjectId($Data)
      {
        $this->iWGSubjectId= $Data;     
      }    
       
      function getWGSubjectName()
      {
        return $this->sWGSubjectName;
      }
      function setWGSubjectName($Data)
      {
        $this->sWGSubjectName= $Data;     
      }          
   
     function getWGCategory()
      {
        return $this->sWGCategory;
      }
      function setWGCategory($Data)
      {
        $this->sWGCategory= $Data;     
      } 
      
       function getWGSubCategory()
      {
        return $this->sWGSubCategory;
      }
      function setWGSubCategory($Data)
      {
        $this->sWGSubCategory= $Data;     
      } 
}
?>