<?php


//   This class is generated by Class Automation System


//	Class Name             :   clsStudentDetailManager


//	Type                   :   Manager Class


//	Description            :   This class implements the methods for DML operations of table clsDegreeDetailManager


//	Author                 :   Ashutosh Kumar Choubey


//	Date                   :   08/09/2011


//	Modified By            :   


//	Date of Modification   :   


//	Purpose of Modification:  


require_once ($_SERVER['DOCUMENT_ROOT']."/Science/CProgramming/classes/clsWGSubject.php");


require_once ($_SERVER['DOCUMENT_ROOT']."/Science/CProgramming/classes/clsWGSubjectSet.php");


class clsWGSubjectManeger


{


   function RetrieveWGSubjectSet($sQuery)


   {


        global $DOCUMENT_ROOT;


        require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");


        $objWGSubjectSet=new clsWGSubjectSet();


        $objWGSubject=new clsWGSubject();


        $rslWGSubject = mysqli_query($connection,$sQuery) or die ("Couldn't execute query in clsWGSubjectManeger:RetrieveWGSubjectSet.");


        $lNumRows = mysqli_num_rows($rslWGSubject);


        if($lNumRows == 0)


        {


            mysqli_close();


            return $objWGSubjectSet;


        }


        for($lCount = 0; $lCount < $lNumRows; $lCount++)


        {             


            $objWGSubject=new clsWGSubject();


            $arrWGSubject=mysqli_fetch_assoc($rslWGSubject);            


            $objWGSubject->setWGSubjectId($arrWGSubject[wgsubjectid]);        


            $objWGSubject->setWGSubjectName($arrWGSubject[wgsubjectname]);


            $objWGSubject->setWGCategory($arrWGSubject[wgcategory]);


            $objWGSubject->setWGSubCategory($arrWGSubject[wgsubcategory]);        


            $objWGSubjectSet->Add($objWGSubject);


        }


        mysqli_close();


        return $objWGSubjectSet;


    }





    


}


?>