<?php


//   This class is generated by Class Automation System


//	Class Name             :   clsStudentDetailManager


//	Type                   :   Manager Class


//	Description            :   This class implements the methods for DML operations of table clsDegreeDetailManager


//	Author                 :   Ashutosh Kumar Choubey


//	Date                   :   08/09/2011


//	Modified By            :   


//	Date of Modification   :   


//	Purpose of Modification:  


require_once ($_SERVER['DOCUMENT_ROOT']."/Science/CProgramming/classes/clsWGAddTutorial.php");


require_once ($_SERVER['DOCUMENT_ROOT']."/Science/CProgramming/classes/clsWGAddTutorialSet.php");


class clsAddTutorialManager


{


    function SaveTutorial($objSaveTutorial, $myConn=null)//This function save the Student details in database//


    {        


        $iWGUserId=$objSaveTutorial->getWGUserId();


        $sWGUserType=$objSaveTutorial->getWGUserType();        


        $sWGCategory=$objSaveTutorial->getWGCategory();         


        $sWGSubCategory=$objSaveTutorial->getWGSubCategory();         


        $sWGSubject=$objSaveTutorial->getWGSubject();         


        $sWGTitle=$objSaveTutorial->getWGTitle();            


        $sWGDiscription=$objSaveTutorial->getWGDiscription();         


        $sWGFileName=$objSaveTutorial->getWGFileName();      


        $sWGFileType=$objSaveTutorial->getWGFileType();


        $sWGSubTitle=$objSaveTutorial->getWGSubTitle();


        $dtWGtime=$objSaveTutorial->getWGtime();


                   


        if($iWGUserId==null)


            $iWGUserId=' '; 


                    


            


        if($sWGUserType==null)


            $sWGUserType=' ';


        else


            $sWGUserType="'$sWGUserType'";


             


        if($sWGCategory==null)


            $sWGCategory=' ';


        else


            $sWGCategory="'$sWGCategory'";


             


        if($sWGSubCategory==null)


            $sWGSubCategory=' ';


        else


            $sWGSubCategory="'$sWGSubCategory'";


             


        if($sWGSubject==null)


            $sWGSubject=' ';


        else


            $sWGSubject="'$sWGSubject'";


             


        if($sWGTitle==null)


            $sWGTitle=' ';


        else


            $sWGTitle="'$sWGTitle'";


             


        if($sWGDiscription==null)


            $sWGDiscription="' '";


        else


            $sWGDiscription="'$sWGDiscription'";


             


             


        if($sWGFileName==null)


            $sWGFileName="' '";


        else


            $sWGFileName="'$sWGFileName'";


             


        if($sWGFileType==null)


            $sWGFileType="' '";


        else 


            $sWGFileType="'$sWGFileType'";


        if($sWGSubTitle==null)


            $sWGSubTitle="' '";


        else 


            $sWGSubTitle="'$sWGSubTitle'";


            


        if($dtWGtime==null)


            $dtWGtime="' '";


        else 


            $dtWGtime="'$dtWGtime'";


        


        


        $sQuery="insert into wgaddtutorial(wguserid,wgusertype,wgcategory,wgsubcategory,wgsubject,wgtitle,wgdiscription,wgfilename,wgfiletype,Subtitle) values($sWGFileType,$sWGUserType,$sWGCategory,$sWGSubCategory,$sWGSubject,$sWGTitle,$sWGDiscription,$sWGFileName,$sWGFileType,$sWGSubTitle)";


            echo $sQuery;


            @mysqli_close();


            global $DOCUMENT_ROOT;


            require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");  


            $rsltadded=0;


            if(mysqli_query($connection,$sQuery))


            {


                $rsltadded=1;


            }


            else


            {


                $rsltadded=2;


            }


            mysqli_close();


        return $rsltadded;    


   }


   


    function SaveStudentDetailSet($objSaveTutorialSet, $myConn=null)


	{


		$lNumRecord = $objSaveTutorialSet->GetCount();


		$lTotalTuples = 0;


		if(is_resource($myConn) and get_resource_type($myConn)== 'mysql link')


        {


			for($lCount = 0; $lCount < $lNumRecord; $lCount++)


			{	


                $objSaveTutorial= new clsWGAddTutorial();


              	$objSaveTutorial=$objSaveTutorialSet->GetItem($lCount);


                


                $iWGUserId=$objSaveTutorial->getWGUserId();


                $sWGUserType=$objSaveTutorial->getWGUserType();        


                $sWGCategory=$objSaveTutorial->getWGCategory();         


                $sWGSubCategory=$objSaveTutorial->getWGSubCategory();         


                $sWGSubject=$objSaveTutorial->getWGSubject();         


                $sWGTitle=$objSaveTutorial->getWGTitle();            


                $sWGDiscription=$objSaveTutorial->getWGDiscription();         


                $sWGFileName=$objSaveTutorial->getWGFileName();      


                $sWGFileType=$objSaveTutorial->getWGFileType();      


                


                    


                if($iWGUserId==null)


                    $iWGUserId="' '"; 


                            


                    


                if($sWGUserType==null)


                    $sWGUserType='null';


                else


                    $sWGUserType="'$sWGUserType'";


                     


                if($sWGCategory==null)


                    $sWGCategory='null';


                else


                    $sWGCategory="'$sWGCategory'";


                     


                if($sWGSubCategory==null)


                    $sWGSubCategory='null';


                else


                    $sWGSubCategory="'$sWGSubCategory'";


                     


                if($sWGSubject==null)


                    $sWGSubject='null';


                else


                    $sWGSubject="'$sWGSubject'";


                     


                if($sWGTitle==null)


                    $sWGTitle='null';


                else


                    $sWGTitle="'$sWGTitle'";


                     


                if($sWGDiscription==null)


                    $sWGDiscription='null';


                else


                    $sWGDiscription="'$sWGDiscription'";


                     


                     


                if($sWGFileName==null)


                    $sWGFileName='null';


                else


                    $sWGFileName="'$sWGFileName'";


                     


                if($sWGFileType==null)


                    $sWGFileType="' '";


                else 


                    $sWGFileType="'$sWGFileType'";


        


                $sQuery="insert into wgaddtutorial(wguserid,wgusertype,wgcategory,wgsubcategory,wgsubject,wgtitle,wgdiscription,wgfilename,wgfiletype) values($sWGFileType,$sWGUserType,$sWGCategory,$sWGSubCategory,$sWGSubject,$sWGTitle,$sWGDiscription,$sWGFileName,$sWGFileType)";


       	   	


                  global $DOCUMENT_ROOT;


                  require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");


          


                mysqli($myConn,'begin');


                $rsltwgAddTutorials= mysqli($myConn,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:SaveStudentDetailset");


				$lNumTuples = mysql_num_rows($rsltwgAddTutorials);


				if($lNumTuples !=0)


				{


					$lTotalTuples = $lTotalTuples + 1;


				}


			}


            if($lTotalTuples==$lNumRecord)


            {


				mysqli($myConn,'commit');


				mysql_close();


            }


            else


            {


                mysqli($myConn,'rollback');


                mysql_close();


            }    


		}


		else


		{


			global $DOCUMENT_ROOT;


            require($DOCUMENT_ROOT."/dbconnect.php");


			mysqli($connection,'begin');


			for($lCount = 0; $lCount < $lNumRecord; $lCount++)


			{


        	$objSaveTutorial= new clsWGAddTutorial();


           	$objSaveTutorial=$objSaveTutorialSet->GetItem($lCount);


            


            $iWGUserId=$objSaveTutorial->getWGUserId();


        $sWGUserType=$objSaveTutorial->getWGUserType();        


        $sWGCategory=$objSaveTutorial->getWGCategory();         


        $sWGSubCategory=$objSaveTutorial->getWGSubCategory();         


        $sWGSubject=$objSaveTutorial->getWGSubject();         


        $sWGTitle=$objSaveTutorial->getWGTitle();            


        $sWGDiscription=$objSaveTutorial->getWGDiscription();         


        $sWGFileName=$objSaveTutorial->getWGFileName();      


        $sWGFileType=$objSaveTutorial->getWGFileType();      


        


            


        if($iWGUserId==null)


            $iWGUserId="' '"; 


                    


            


        if($sWGUserType==null)


            $sWGUserType='null';


        else


            $sWGUserType="'$sWGUserType'";


             


        if($sWGCategory==null)


            $sWGCategory='null';


        else


            $sWGCategory="'$sWGCategory'";


             


        if($sWGSubCategory==null)


            $sWGSubCategory='null';


        else


            $sWGSubCategory="'$sWGSubCategory'";


             


        if($sWGSubject==null)


            $sWGSubject='null';


        else


            $sWGSubject="'$sWGSubject'";


             


        if($sWGTitle==null)


            $sWGTitle='null';


        else


            $sWGTitle="'$sWGTitle'";


             


        if($sWGDiscription==null)


            $sWGDiscription='null';


        else


            $sWGDiscription="'$sWGDiscription'";


             


             


        if($sWGFileName==null)


            $sWGFileName='null';


        else


            $sWGFileName="'$sWGFileName'";


             


        if($sWGFileType==null)


            $sWGFileType="' '";


        else 


            $sWGFileType="'$sWGFileType'";


        


        $sQuery="insert into wgaddtutorial(wguserid,wgusertype,wgcategory,wgsubcategory,wgsubject,wgtitle,wgdiscription,wgfilename,wgfiletype) values($sWGFileType,$sWGUserType,$sWGCategory,$sWGSubCategory,$sWGSubject,$sWGTitle,$sWGDiscription,$sWGFileName,$sWGFileType)";


       	   


          


                $rsltAddTutorial = mysqli($connection,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:SaveStudentDetailSet");


				$lNumTuples = mysql_num_rows($rsltAddTutorial);


				if($lNumTuples !=0)


				{


					$lTotalTuples = $lTotalTuples + 1;


				}


			}


            if($lTotalTuples==$lNumRecord)


            {


				mysqli($connection,'commit');


				mysqli_close();


            }


            else


            {


                mysqli($connection,'rollback');


                mysqli_close();


            }


		}


			return $lTotalTuples;


	}





   function RetrieveWGAddTutorialSet($sQuery)


   {


        global $DOCUMENT_ROOT;


        require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");    


        $objADDTutorialSet= new clsWGAddTutorialSet();


        $rslAddTutorials = mysqli_query($connection,$sQuery) or die ("Couldn't execute query in clsWGAddTutorialManager:RetrieveWGAddTutorialSet.");


        $lNumRows = mysqli_num_rows($rslAddTutorials);


        if($lNumRows == 0)


        {


            mysqli_close();


            return $objADDTutorialSet;


        }


        for($lCount = 0; $lCount < $lNumRows; $lCount++)


        {


            $objADDTutorial=new clsWGAddTutorial();


            $arrAddTutorial=mysqli_fetch_array($rslAddTutorials,MYSQL_ASSOC);            


            $objADDTutorial->setWGUserId($arrAddTutorial[wguserid]);        


            $objADDTutorial->setWGUserType($arrAddTutorial[wgusertype]);         


            $objADDTutorial->setWGCategory($arrAddTutorial[wgcategory]);         


            $objADDTutorial->setWGSubCategory($arrAddTutorial[wgsubcategory]);         


            $objADDTutorial->setWGSubject($arrAddTutorial[wgsubject]);            


            $objADDTutorial->setWGTitle($arrAddTutorial[wgtitle]);         


            $objADDTutorial->setWGDiscription($arrAddTutorial[wgdiscription]);      


            $objADDTutorial->setWGFileName($arrAddTutorial[wgfilename]);      


            $objADDTutorial->setWGFileType($arrAddTutorial[wgfiletype]); 


            $objADDTutorialSet->Add($objADDTutorial);


        }


        mysqli_close();


        return $objADDTutorialSet;


    }





     function RetrieveWGAddTutorial($sQuery)


     {


        global $DOCUMENT_ROOT;


        require($_SERVER['DOCUMENT_ROOT']."/dbconnect.php");    


        $objADDTutorialSet= new clsWGAddTutorialSet();


        $rslAddTutorials = mysqli_query($connection,$sQuery) or die ("Couldn't execute query in clsAddTutorialManager:RetrieveWGAddTutorialSet.");


        $lNumRows = mysqli_num_rows($rslAddTutorials);


        if($lNumRows == 0)


        {


            mysqli_close();


            return $objADDTutorialSet;


        }


        for($lCount = 0; $lCount < $lNumRows; $lCount++)


        {


            $objADDTutorial=new clsWGAddTutorial();


            $arrAddTutorial=mysqli_fetch_array($rslAddTutorials,MYSQL_ASSOC);            


            $objADDTutorial->setSDRollNum($arrAddTutorial[]);        


            $objADDTutorial->setSDFName($arrAddTutorial[sdfname]);         


            $objADDTutorial->setSDMName($arrAddTutorial[sdmname]);         


            $objADDTutorial->setSDLName($arrAddTutorial[sdlname]);         


            $objADDTutorial->setSDSex($arrAddTutorial[sdsex]);            


            $objADDTutorial->setDDDegName($arrAddTutorial[dddegname]);         


            $objADDTutorial->setBDBranchCode($arrAddTutorial[bdbranchcode]);      


            $objADDTutorial->setSDBatchYear($arrAddTutorial[sdbatchyear]);      


            $objADDTutorial->setSDAddress($arrAddTutorial[sdaddress]);         


            $objADDTutorial->setSDMobNum($arrAddTutorial[sdmobnum]); 


        }


        mysqli_close();


        return $objADDTutorial;


    }


    function UpdateStudentDetail($objStudentDetail, $myConn=null)


	{


		global $DOCUMENT_ROOT;





	


			    $iSDShortRoll=$objStudentDetail->getSDShortRoll();


                $iSDRollNum=$objStudentDetail->getSDRollNum();        


                $sSDFName=$objStudentDetail->getSDFName();         


                $sSDMName=$objStudentDetail->getSDMName();         


                $sSDLName=$objStudentDetail->getSDLName();         


                $sSDSex=$objStudentDetail->getSDSex();            


                $sDDDegName=$objStudentDetail->getDDDegName();         


                $sBDBranchCode=$objStudentDetail->getBDBranchCode();      


                $iSDBatchYear=$objStudentDetail->getSDBatchYear();      


                $sSDAddress=$objStudentDetail->getSDAddress();         


                $sSDMobNum=$objStudentDetail->getSDMobNum(); 


                


                    


                if($iSDShortRoll==null)


                    $iSDShortRoll='null';


                             


                if($iSDRollNum==null)


                    $iSDRollNum='null';


                    


                if($sSDFName==null)


                    $sSDFName='null';


                else


                    $sSDFName="'$sSDFName'";


                     


                if($sSDMName==null)


                    $sSDMName='null';


                else


                    $sSDMName="'$sSDMName'";


                     


                if($sSDLName==null)


                    $sSDLName='null';


                else


                    $sSDLName="'$sSDLName'";


                     


                if($sSDSex==null)


                    $sSDSex='null';


                else


                    $sSDSex="'$sSDSex'";


                     


                if($sDDDegName==null)


                    $sDDDegName='null';


                else


                    $sDDDegName="'$sDDDegName'";


                     


                if($sBDBranchCode==null)


                    $sBDBranchCode='null';


                else


                    $sBDBranchCode="$sBDBranchCode";


                     


                if($iSDBatchYear==null)


                    $iSDBatchYear='null';


                


                if($sSDAddress==null)


                    $sSDAddress='null';


                else


                    $sSDAddress="'$sSDAddress'";


                     


                if($sSDMobNum==null)


                    $sSDMobNum='null';


                else


                    $sSDMobNum="'$sSDMobNum'";  


                


				$sQuery = "update studentdetail set                


				sdrollnum=$iSDRollNum,


				sdfname=$sSDFName,


				sdmname=$sSDMName,


				sdlname=$sSDLName,


				sdsex=$sSDSex,


                dddegname=$sDDDegName,


                bdbranchcode=$sBDBranchCode,


                sdbatchyear=$iSDBatchYear,


                sdaddress=$sSDAddress,


                sdmobnum=$sSDMobNum


				where sdrollnum=$iSDRollNum";


			


		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')


		{


			$rsltStudentDetail = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:UpdateStudentDetail");


			$lNumTuples = pg_cmdtuples($rsltStudentDetail);


		}


		else


		{


			@pg_close();


			global $DOCUMENT_ROOT;


			require($DOCUMENT_ROOT."/ois/dbconnect.php");


			$rsltStudentDetail = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:UpdateStudentDetail");


			$lNumTuples = pg_cmdtuples($rsltStudentDetail);


			pg_close();


		}


	return $lNumTuples;


	}


	function UpdateStudentDetailSet($objStudentDetailSet, $myConn=null)


	{


	    $lNumRecord = $objStudentDetailSet->GetCount();


		$lTotalTuples = 0;


		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')


        {


			for($lCount = 0; $lCount < $lNumRecord; $lCount++)


			{


			    $objStudentDetail= new clsStudentDetail();


                $objStudentDetail=$objStudentDetailSet->GetItem($lCount);


                


				$iSDShortRoll=$objStudentDetail->getSDShortRoll();


                $iSDRollNum=$objStudentDetail->getSDRollNum();        


                $sSDFName=$objStudentDetail->getSDFName();         


                $sSDMName=$objStudentDetail->getSDMName();         


                $sSDLName=$objStudentDetail->getSDLName();         


                $sSDSex=$objStudentDetail->getSDSex();            


                $sDDDegName=$objStudentDetail->getDDDegName();         


                $sBDBranchCode=$objStudentDetail->getBDBranchCode();      


                $iSDBatchYear=$objStudentDetail->getSDBatchYear();      


                $sSDAddress=$objStudentDetail->getSDAddress();         


                $sSDMobNum=$objStudentDetail->getSDMobNum(); 


                


                    


                if($iSDShortRoll)


                    $iSDShortRoll='null'; 


                            


                if($iSDRollNum==null)


                    $iSDRollNum='null';


                    


                if($sSDFName==null)


                    $sSDFName='null';


                else


                    $sSDFName="'$sSDFName'";


                     


                if($sSDMName==null)


                    $sSDMName='null';


                else


                    $sSDMName="'$sSDMName'";


                     


                if($sSDLName==null)


                    $sSDLName='null';


                else


                    $sSDLName="'$sSDLName'";


                     


                if($sSDSex==null)


                    $sSDSex='null';


                else


                    $sSDSex="'$sSDSex'";


                     


                if($sDDDegName==null)


                    $sDDDegName='null';


                else


                    $sDDDegName="'$sDDDegName'";


                     


                if($sBDBranchCode==null)


                    $sBDBranchCode='null';


                else


                    $sBDBranchCode="'$sBDBranchCode'";


                     


                if($iSDBatchYear==null)


                    $iSDBatchYear='null';


                                     


                if($sSDAddress==null)


                    $sSDAddress='null';


                else


                    $sSDAddress="'$sSDAddress'";


                     


                if($sSDMobNum==null)


                    $sSDMobNum='null';


                else


                    $sSDMobNum="'$sSDMobNum'";


                


			$sQuery = "update studentdetail set                


				sdrollnum=$iSDRollNum,


				sdfname=$sSDFName,


				sdmname=$sSDMName,


				sdlname=$sSDLName,


				sdsex=$sSDSex,


                dddegname=$sDDDegName,


                bdbranchcode=$sBDBranchCode,


                sdbatchyear=$iSDBatchYear,


                sdaddress=$sSDAddress,


                sdmobnum=$sSDMobNum


				where sdrollnum=$iSDRollNum";


                pg_exec($myConn,'begin');


				$rsltStudentDetail = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:UpdateStudentDetailSet");


				$lNumTuples = pg_cmdtuples($rsltStudentDetail);


				if($lNumTuples !=0)


				{


					$lTotalTuples = $lTotalTuples + 1;


				}


			}


            if($lTotalTuples==$lNumRecord)


            {


				pg_exec($myConn,'commit');


				pg_close();


            }


            else


            {


				pg_exec($myConn,'rollback');


				pg_close();


            }


		}


		else


		{


			global $DOCUMENT_ROOT;


			require($_SERVER['DOCUMENT_ROOT']."/ois/dbconnect.php");


			pg_exec($connection,'begin');


			for($lCount = 0; $lCount < $lNumRecord; $lCount++)


			{


				$objStudentDetail=new clsStudentDetail();


		        $objStudentDetail=$objStudentDetailSet->GetItem($lCount);


				


				$iSDShortRoll=$objStudentDetail->getSDShortRoll();


                $iSDRollNum=$objStudentDetail->getSDRollNum();        


                $sSDFName=$objStudentDetail->getSDFName();         


                $sSDMName=$objStudentDetail->getSDMName();         


                $sSDLName=$objStudentDetail->getSDLName();         


                $sSDSex=$objStudentDetail->getSDSex();            


                $sDDDegName=$objStudentDetail->getDDDegName();         


                $sBDBranchCode=$objStudentDetail->getBDBranchCode();      


                $iSDBatchYear=$objStudentDetail->getSDBatchYear();      


                $sSDAddress=$objStudentDetail->getSDAddress();         


                $sSDMobNum=$objStudentDetail->getSDMobNum(); 


                


                    


                if($iSDShortRoll)


                    $iSDShortRoll='null'; 


                            


                if($iSDRollNum==null)


                    $iSDRollNum='null';


                    


                if($sSDFName==null)


                    $sSDFName='null';


                else


                    $sSDFName="'$sSDFName'";


                     


                if($sSDMName==null)


                    $sSDMName='null';


                else


                    $sSDMName="'$sSDMName'";


                     


                if($sSDLName==null)


                    $sSDLName='null';


                else


                    $sSDLName="'$sSDLName'";


                     


                if($sSDSex==null)


                    $sSDSex='null';


                else


                    $sSDSex="'$sSDSex'";


                     


                if($sDDDegName==null)


                    $sDDDegName='null';


                else


                    $sDDDegName="'$sDDDegName'";


                     


                if($sBDBranchCode==null)


                    $sBDBranchCode='null';


                else


                    $sBDBranchCode="'$sBDBranchCode'";


                     


                if($iSDBatchYear==null)


                    $iSDBatchYear='null';


                                     


                if($sSDAddress==null)


                    $sSDAddress='null';


                else


                    $sSDAddress="'$sSDAddress'";


                     


                if($sSDMobNum==null)


                    $sSDMobNum='null';


                else 


                    $sSDMobNum="'$sSDMobNum'";


                    


				$sQuery = "update studentdetail set                


				sdrollnum=$iSDRollNum,


				sdfname=$sSDFName,


				sdmname=$sSDMName,


				sdlname=$sSDLName,


				sdsex=$sSDSex,


                dddegname=$sDDDegName,


                bdbranchcode=$sBDBranchCode,


                sdbatchyear=$iSDBatchYear,


                sdaddress=$sSDAddress,


                sdmobnum=$sSDMobNum


				where sdrollnum=$iSDRollNum";


                pg_exec($connection,'begin');


				$rsltStudentDetail= pg_exec($connection,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:UpdateStudentDetailSet");


				$lNumTuples = pg_cmdtuples($rsltStudentDetail);


				if($lNumTuples !=0)


				{


					$lTotalTuples = $lTotalTuples + 1;


				}


			}


            if($lTotalTuples==$lNumRecord)


            {


				pg_exec($connection,'commit');


				pg_close();


            }


            else


            {


				pg_exec($connection,'rollback');


				pg_close();


            }


		}


			return $lTotalTuples;


	}


	function DeleteStudentDetail($objStudentDetail, $myConn=null)


	{


	   global $DOCUMENT_ROOT;


	


     	$iSDRollNum=$objStudentDetail->getSDRollNum();


                


        if($iSDRollNum==null)


        $iSDRollNums='null';


            


        $sQuery = "delete from studentdetail where sdrollnum=$iSDRollNum";


               


		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')


		{


			$rsltStudentDetail = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:DeleteStudentDetail");


			$lNumTuples = pg_cmdtuples($rsltStudentDetail);


		}


		else


		{


			@pg_close();


			global $DOCUMENT_ROOT;


			require($DOCUMENT_ROOT."/ois/dbconnect.php");


			$rsltStudentDetail = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:DeleteStudentDetail");


			$lNumTuples = pg_cmdtuples($rsltStudentDetail);


			pg_close();


		}


	 return $lNumTuples;


	}


    //Added by Ashutosh kumar choubey to Delete multiple students Detail


    function DeleteStudentDetailSet($objStudentDetailSet, $myConn=null)


	{


		$lNumRecord=$objStudentDetailSet->GetCount();


		$lTotalTuples = 0;


        


		if(is_resource($myConn) and get_resource_type($myConn)== 'pgsql link')


		{


			for($lCount = 0; $lCount < $lNumRecord; $lCount++)


			{


				$objStudentDetail=new clsStudentDetail();


		        $objStudentDetail=$objStudentDetailSet->GetItem($lCount);


				


				$iSDRollNum=$objStudentDetail->getSDRollNum();


                


                if($iSDRollNum==null)


                    $iSDRollNums='null';


            


                $sQuery = "delete from studentdetail where sdrollnum=$iSDRollNum";


                pg_exec($myConn,'begin');


                $rsltStudentDetail = pg_exec($myConn,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:DeleteStudentDetailSet");


    			$lNumTuples = pg_cmdtuples($rsltStudentDetail);


				if($lNumTuples !=0)


				{


					$lTotalTuples = $lTotalTuples + 1;


				}                


    		}


            if($lTotalTuples==$lNumRecord)


            {


    			pg_exec($myConn,'commit');


    			pg_close();


            }


            else


            {


                pg_exec($myConn,'rollback');


                pg_close();


            }


        }


		else


		{


			global $DOCUMENT_ROOT;


			require($DOCUMENT_ROOT."/ois/dbconnect.php");


			pg_exec($connection,'begin');


			for($lCount = 0; $lCount < $lNumRecord; $lCount++)


			{


				$objStudentDetail=new clsStudentDetail();


		        $objStudentDetail=$objStudentDetailSet->GetItem($lCount);


				


				$iSDRollNum=$objStudentDetail->getSDRollNum();


                


                if($iSDRollNum==null)


                    $iSDRollNums='null';


            


                $sQuery = "delete from studentdetail where sdrollnum=$iSDRollNum";


                


                $rsltStudentDetail = pg_exec($connection,$sQuery) or die ("Couldn't execute query in clsStudentDetailManager:DeleteStudentDetailSet");


                $lNumTuples = pg_cmdtuples($rsltStudentDetail);


				if($lNumTuples !=0)


				{


					$lTotalTuples = $lTotalTuples + 1;


				}                


			}


            if($lTotalTuples==$lNumRecord)


            {


    			pg_exec($connection,'commit');


    			pg_close();


            }


            else


            {


                pg_exec($connection,'rollback');


                pg_close();


            }


		}


        return $lTotalTuples;


	}





}


?>